<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrew Walther">
<meta name="dcterms.date" content="2026-03-22">

<title>Personalized Design Recommendation Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="09_MLE_design_recommendation_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="09_MLE_design_recommendation_report_files/libs/quarto-html/quarto.js"></script>
<script src="09_MLE_design_recommendation_report_files/libs/quarto-html/popper.min.js"></script>
<script src="09_MLE_design_recommendation_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="09_MLE_design_recommendation_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="09_MLE_design_recommendation_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="09_MLE_design_recommendation_report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="09_MLE_design_recommendation_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="09_MLE_design_recommendation_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="09_MLE_design_recommendation_report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="09_MLE_design_recommendation_report_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="09_MLE_design_recommendation_report_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive Summary</a></li>
  <li><a href="#study-background" id="toc-study-background" class="nav-link" data-scroll-target="#study-background"><span class="header-section-number">2</span> Study Background</a>
  <ul class="collapse">
  <li><a href="#designs-evaluated" id="toc-designs-evaluated" class="nav-link" data-scroll-target="#designs-evaluated"><span class="header-section-number">2.1</span> Designs Evaluated</a></li>
  <li><a href="#performance-metrics" id="toc-performance-metrics" class="nav-link" data-scroll-target="#performance-metrics"><span class="header-section-number">2.2</span> Performance Metrics</a></li>
  <li><a href="#simulation-parameter-space" id="toc-simulation-parameter-space" class="nav-link" data-scroll-target="#simulation-parameter-space"><span class="header-section-number">2.3</span> Simulation Parameter Space</a></li>
  </ul></li>
  <li><a href="#analytical-methods" id="toc-analytical-methods" class="nav-link" data-scroll-target="#analytical-methods"><span class="header-section-number">3</span> Analytical Methods</a>
  <ul class="collapse">
  <li><a href="#core-ranking-method-rank_designs_by_group" id="toc-core-ranking-method-rank_designs_by_group" class="nav-link" data-scroll-target="#core-ranking-method-rank_designs_by_group"><span class="header-section-number">3.1</span> Core Ranking Method: <code>rank_designs_by_group()</code></a></li>
  <li><a href="#q1-per-config-rankings-table_incidence_rankings-and-plot_incidence_rankings" id="toc-q1-per-config-rankings-table_incidence_rankings-and-plot_incidence_rankings" class="nav-link" data-scroll-target="#q1-per-config-rankings-table_incidence_rankings-and-plot_incidence_rankings"><span class="header-section-number">3.2</span> Q1 — Per-Config Rankings: <code>table_incidence_rankings()</code> and <code>plot_incidence_rankings()</code></a></li>
  <li><a href="#q2-marginal-rankings-table_marginal_rankings-and-plot_rank_trajectories" id="toc-q2-marginal-rankings-table_marginal_rankings-and-plot_rank_trajectories" class="nav-link" data-scroll-target="#q2-marginal-rankings-table_marginal_rankings-and-plot_rank_trajectories"><span class="header-section-number">3.3</span> Q2 — Marginal Rankings: <code>table_marginal_rankings()</code> and <code>plot_rank_trajectories()</code></a></li>
  <li><a href="#q3-best-design-heatmap-plot_best_design_heatmap" id="toc-q3-best-design-heatmap-plot_best_design_heatmap" class="nav-link" data-scroll-target="#q3-best-design-heatmap-plot_best_design_heatmap"><span class="header-section-number">3.4</span> Q3 — Best Design Heatmap: <code>plot_best_design_heatmap()</code></a></li>
  <li><a href="#programmatic-commentary-generate_commentary" id="toc-programmatic-commentary-generate_commentary" class="nav-link" data-scroll-target="#programmatic-commentary-generate_commentary"><span class="header-section-number">3.5</span> Programmatic Commentary: <code>generate_commentary()</code></a></li>
  </ul></li>
  <li><a href="#q1-design-rankings-by-incidence-mode" id="toc-q1-design-rankings-by-incidence-mode" class="nav-link" data-scroll-target="#q1-design-rankings-by-incidence-mode"><span class="header-section-number">4</span> Q1: Design Rankings by Incidence Mode</a>
  <ul class="collapse">
  <li><a href="#cross-config-mse-rankings" id="toc-cross-config-mse-rankings" class="nav-link" data-scroll-target="#cross-config-mse-rankings"><span class="header-section-number">4.1</span> Cross-Config MSE Rankings</a></li>
  <li><a href="#cross-config-coverage-rankings" id="toc-cross-config-coverage-rankings" class="nav-link" data-scroll-target="#cross-config-coverage-rankings"><span class="header-section-number">4.2</span> Cross-Config Coverage Rankings</a></li>
  <li><a href="#detailed-rankings-by-incidence-config" id="toc-detailed-rankings-by-incidence-config" class="nav-link" data-scroll-target="#detailed-rankings-by-incidence-config"><span class="header-section-number">4.3</span> Detailed Rankings by Incidence Config</a></li>
  </ul></li>
  <li><a href="#q2-marginal-rankings-by-parameter-level" id="toc-q2-marginal-rankings-by-parameter-level" class="nav-link" data-scroll-target="#q2-marginal-rankings-by-parameter-level"><span class="header-section-number">5</span> Q2: Marginal Rankings by Parameter Level</a>
  <ul class="collapse">
  <li><a href="#effect-of-outcome-spatial-autocorrelation-rho" id="toc-effect-of-outcome-spatial-autocorrelation-rho" class="nav-link" data-scroll-target="#effect-of-outcome-spatial-autocorrelation-rho"><span class="header-section-number">5.1</span> Effect of Outcome Spatial Autocorrelation (Rho)</a></li>
  <li><a href="#effect-of-spillover-magnitude-gamma" id="toc-effect-of-spillover-magnitude-gamma" class="nav-link" data-scroll-target="#effect-of-spillover-magnitude-gamma"><span class="header-section-number">5.2</span> Effect of Spillover Magnitude (Gamma)</a></li>
  <li><a href="#marginal-ranking-tables" id="toc-marginal-ranking-tables" class="nav-link" data-scroll-target="#marginal-ranking-tables"><span class="header-section-number">5.3</span> Marginal Ranking Tables</a>
  <ul class="collapse">
  <li><a href="#iid-uniform" id="toc-iid-uniform" class="nav-link" data-scroll-target="#iid-uniform"><span class="header-section-number">5.3.1</span> iid Uniform</a></li>
  <li><a href="#poisson-rho_x-0.20" id="toc-poisson-rho_x-0.20" class="nav-link" data-scroll-target="#poisson-rho_x-0.20"><span class="header-section-number">5.3.2</span> Poisson (rho_X = 0.20)</a></li>
  <li><a href="#poisson-rho_x-0.50" id="toc-poisson-rho_x-0.50" class="nav-link" data-scroll-target="#poisson-rho_x-0.50"><span class="header-section-number">5.3.3</span> Poisson (rho_X = 0.50)</a></li>
  <li><a href="#spatial-rho_x-0.20" id="toc-spatial-rho_x-0.20" class="nav-link" data-scroll-target="#spatial-rho_x-0.20"><span class="header-section-number">5.3.4</span> Spatial (rho_X = 0.20)</a></li>
  <li><a href="#spatial-rho_x-0.50" id="toc-spatial-rho_x-0.50" class="nav-link" data-scroll-target="#spatial-rho_x-0.50"><span class="header-section-number">5.3.5</span> Spatial (rho_X = 0.50)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#q3-best-design-for-parameter-combinations" id="toc-q3-best-design-for-parameter-combinations" class="nav-link" data-scroll-target="#q3-best-design-for-parameter-combinations"><span class="header-section-number">6</span> Q3: Best Design for Parameter Combinations</a>
  <ul class="collapse">
  <li><a href="#rho-x-gamma-best-design-maps" id="toc-rho-x-gamma-best-design-maps" class="nav-link" data-scroll-target="#rho-x-gamma-best-design-maps"><span class="header-section-number">6.1</span> Rho x Gamma Best-Design Maps</a></li>
  <li><a href="#rho-x-spillover-type-best-design-maps" id="toc-rho-x-spillover-type-best-design-maps" class="nav-link" data-scroll-target="#rho-x-spillover-type-best-design-maps"><span class="header-section-number">6.2</span> Rho x Spillover Type Best-Design Maps</a></li>
  </ul></li>
  <li><a href="#per-config-narrative-findings" id="toc-per-config-narrative-findings" class="nav-link" data-scroll-target="#per-config-narrative-findings"><span class="header-section-number">7</span> Per-Config Narrative Findings</a>
  <ul class="collapse">
  <li><a href="#iid-uniform-1" id="toc-iid-uniform-1" class="nav-link" data-scroll-target="#iid-uniform-1"><span class="header-section-number">7.1</span> iid Uniform</a></li>
  <li><a href="#poisson-rho_x-0.20-1" id="toc-poisson-rho_x-0.20-1" class="nav-link" data-scroll-target="#poisson-rho_x-0.20-1"><span class="header-section-number">7.2</span> Poisson (rho_X = 0.20)</a></li>
  <li><a href="#poisson-rho_x-0.50-1" id="toc-poisson-rho_x-0.50-1" class="nav-link" data-scroll-target="#poisson-rho_x-0.50-1"><span class="header-section-number">7.3</span> Poisson (rho_X = 0.50)</a></li>
  <li><a href="#spatial-rho_x-0.20-1" id="toc-spatial-rho_x-0.20-1" class="nav-link" data-scroll-target="#spatial-rho_x-0.20-1"><span class="header-section-number">7.4</span> Spatial (rho_X = 0.20)</a></li>
  <li><a href="#spatial-rho_x-0.50-1" id="toc-spatial-rho_x-0.50-1" class="nav-link" data-scroll-target="#spatial-rho_x-0.50-1"><span class="header-section-number">7.5</span> Spatial (rho_X = 0.50)</a></li>
  </ul></li>
  <li><a href="#scenario-specific-design-lookup" id="toc-scenario-specific-design-lookup" class="nav-link" data-scroll-target="#scenario-specific-design-lookup"><span class="header-section-number">8</span> Scenario-Specific Design Lookup</a>
  <ul class="collapse">
  <li><a href="#iid-uniform-2" id="toc-iid-uniform-2" class="nav-link" data-scroll-target="#iid-uniform-2"><span class="header-section-number">8.1</span> iid Uniform</a></li>
  <li><a href="#poisson-rho_x-0.20-2" id="toc-poisson-rho_x-0.20-2" class="nav-link" data-scroll-target="#poisson-rho_x-0.20-2"><span class="header-section-number">8.2</span> Poisson (rho_X = 0.20)</a></li>
  <li><a href="#poisson-rho_x-0.50-2" id="toc-poisson-rho_x-0.50-2" class="nav-link" data-scroll-target="#poisson-rho_x-0.50-2"><span class="header-section-number">8.3</span> Poisson (rho_X = 0.50)</a></li>
  <li><a href="#spatial-rho_x-0.20-2" id="toc-spatial-rho_x-0.20-2" class="nav-link" data-scroll-target="#spatial-rho_x-0.20-2"><span class="header-section-number">8.4</span> Spatial (rho_X = 0.20)</a></li>
  <li><a href="#spatial-rho_x-0.50-2" id="toc-spatial-rho_x-0.50-2" class="nav-link" data-scroll-target="#spatial-rho_x-0.50-2"><span class="header-section-number">8.5</span> Spatial (rho_X = 0.50)</a></li>
  </ul></li>
  <li><a href="#practical-design-selection-guide" id="toc-practical-design-selection-guide" class="nav-link" data-scroll-target="#practical-design-selection-guide"><span class="header-section-number">9</span> Practical Design Selection Guide</a>
  <ul class="collapse">
  <li><a href="#decision-framework" id="toc-decision-framework" class="nav-link" data-scroll-target="#decision-framework"><span class="header-section-number">9.1</span> Decision Framework</a></li>
  <li><a href="#why-d3-sat.-quadrants-wins-mechanistic-explanation" id="toc-why-d3-sat.-quadrants-wins-mechanistic-explanation" class="nav-link" data-scroll-target="#why-d3-sat.-quadrants-wins-mechanistic-explanation"><span class="header-section-number">9.2</span> Why D3: Sat. Quadrants Wins: Mechanistic Explanation</a></li>
  <li><a href="#why-d1-checkerboard-fails-mechanistic-explanation" id="toc-why-d1-checkerboard-fails-mechanistic-explanation" class="nav-link" data-scroll-target="#why-d1-checkerboard-fails-mechanistic-explanation"><span class="header-section-number">9.3</span> Why D1: Checkerboard Fails: Mechanistic Explanation</a></li>
  </ul></li>
  <li><a href="#summary-of-key-results" id="toc-summary-of-key-results" class="nav-link" data-scroll-target="#summary-of-key-results"><span class="header-section-number">10</span> Summary of Key Results</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">11</span> References</a></li>
  <li><a href="#appendix-output-files" id="toc-appendix-output-files" class="nav-link" data-scroll-target="#appendix-output-files"><span class="header-section-number">12</span> Appendix: Output Files</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="09_MLE_design_recommendation_report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Personalized Design Recommendation Report</h1>
<p class="subtitle lead">MLE-Based Analysis for Spatial CRT Treatment Assignment</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrew Walther </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="executive-summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Executive Summary</h1>
<p>This report is a companion to the <code>MLE_combined_design_recommendations.pdf</code> figure file. It provides narrative explanations of <strong>how each analysis was computed</strong>, <strong>what each figure and table shows</strong>, and <strong>what the results mean in practice</strong> for researchers designing spatial cluster randomized trials (CRTs).</p>
<p>The simulation evaluates <strong>8 treatment assignment designs</strong> across <strong>2560 parameter scenarios</strong> using Maximum Likelihood Estimation (MLE) via a spatial autoregressive model (<code>lagsarlm</code>). The estimand is the direct treatment effect <span class="math inline">\(\tau = 1.0\)</span>.</p>
<p>Three analytical questions are addressed:</p>
<div class="cell-output-display">
<table class="table" data-quarto-postprocess="true">
<caption>Best MLE design (lowest avg MSE) for each of the 5 incidence configurations.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Incidence Config</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Best Design</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Avg MSE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Avg Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">iid Uniform</td>
<td style="text-align: left;">D3: Sat. Quadrants</td>
<td style="text-align: right;">0.0768</td>
<td style="text-align: right;">0.939</td>
</tr>
<tr class="even">
<td style="text-align: left;">Poisson (rho_X = 0.20)</td>
<td style="text-align: left;">D8: Inc.-Guided Sat. Q.</td>
<td style="text-align: right;">0.0739</td>
<td style="text-align: right;">0.943</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Poisson (rho_X = 0.50)</td>
<td style="text-align: left;">D8: Inc.-Guided Sat. Q.</td>
<td style="text-align: right;">0.0788</td>
<td style="text-align: right;">0.938</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spatial (rho_X = 0.20)</td>
<td style="text-align: left;">D3: Sat. Quadrants</td>
<td style="text-align: right;">0.0798</td>
<td style="text-align: right;">0.938</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spatial (rho_X = 0.50)</td>
<td style="text-align: left;">D2: High Inc. Focus</td>
<td style="text-align: right;">0.0725</td>
<td style="text-align: right;">0.969</td>
</tr>
</tbody>
</table>


</div>
<p><strong>Key finding:</strong> D3: Sat. Quadrants achieves the lowest average MSE in 2 of 5 incidence configurations, with D1: Checkerboard consistently worst. Spillover type (control-only vs.&nbsp;both) is by far the most influential parameter for all leading designs, while spatial autocorrelation <span class="math inline">\(\rho\)</span> and spillover magnitude <span class="math inline">\(\gamma\)</span> have secondary effects.</p>
</section>
<section id="study-background" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Study Background</h1>
<section id="designs-evaluated" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="designs-evaluated"><span class="header-section-number">2.1</span> Designs Evaluated</h2>
<p>8 treatment assignment strategies are compared. Each allocates approximately 50% of the 100 clusters (<span class="math inline">\(10 \times 10\)</span> grid) to treatment:</p>
<div class="cell-output-display">
<table class="table" data-quarto-postprocess="true">
<caption>8 treatment assignment designs evaluated. Deterministic designs (1, 2) produce one assignment and replicate it; stochastic designs resample across 25 replications.</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Deterministic?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Checkerboard</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left; width: 7cm;">Alternating grid pattern; maximizes spatial separation of treated and control units</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">High Incidence Focus</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left; width: 7cm;">Treats the top-50\% incidence clusters deterministically</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Saturation Quadrants</td>
<td style="text-align: left;">No</td>
<td style="text-align: left; width: 7cm;">Assigns random saturation levels (0.2--0.8) within each of four spatial quadrants</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Isolation Buffer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left; width: 7cm;">Greedy assignment ensuring no two adjacent clusters are both treated</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">2x2 Blocking</td>
<td style="text-align: left;">No</td>
<td style="text-align: left; width: 7cm;">1:1 randomization within non-overlapping 2x2 spatial blocks</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Balanced Quartiles</td>
<td style="text-align: left;">No</td>
<td style="text-align: left; width: 7cm;">Stratified randomization balanced within incidence quartiles</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Balanced Halves</td>
<td style="text-align: left;">No</td>
<td style="text-align: left; width: 7cm;">Stratified randomization balanced within incidence halves (above/below median)</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Incidence-Guided Saturation Quadrants</td>
<td style="text-align: left;">No</td>
<td style="text-align: left; width: 7cm;">NA</td>
</tr>
</tbody>
</table>


</div>
</section>
<section id="performance-metrics" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="performance-metrics"><span class="header-section-number">2.2</span> Performance Metrics</h2>
<p>For each of the 2560 scenarios, <strong>250 simulation iterations</strong> (25 design resamples <span class="math inline">\(\times\)</span> 10 outcome resamples) produce the following metrics:</p>
<ul>
<li><strong>Bias</strong> <span class="math inline">\(= \bar{\hat{\tau}} - \tau\)</span>: average departure from true effect <span class="math inline">\(\tau = 1.0\)</span></li>
<li><strong>SD</strong>: standard deviation of estimates across iterations</li>
<li><strong>MSE</strong> <span class="math inline">\(= \text{Bias}^2 + \text{SD}^2\)</span>: total estimation error; the <strong>primary ranking criterion</strong> throughout this report</li>
<li><strong>Coverage</strong>: fraction of 95% confidence intervals containing <span class="math inline">\(\tau = 1.0\)</span></li>
</ul>
<p>Lower MSE is better. Coverage near 0.95 (the nominal level) indicates valid inference.</p>
</section>
<section id="simulation-parameter-space" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="simulation-parameter-space"><span class="header-section-number">2.3</span> Simulation Parameter Space</h2>
<div class="cell-output-display">
<table class="table" data-quarto-postprocess="true">
<caption>Simulation parameter grid. Each of the 2560 scenarios is a unique combination of (incidence config, nb\_type, Rho, Gamma, Spillover type, Design). Results are always reported separately by incidence config.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Parameter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Levels</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Incidence mode</td>
<td style="text-align: left;">iid, spatial, poisson</td>
<td style="text-align: left;">5 configs</td>
</tr>
<tr class="even">
<td style="text-align: left;">rho\_X (incidence spatial autocorr.)</td>
<td style="text-align: left;">N/A (iid); 0.2, 0.5 (Spatial, Poisson)</td>
<td style="text-align: left;">---</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nb\_type (contiguity)</td>
<td style="text-align: left;">queen, rook</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rho (outcome spatial autocorr.)</td>
<td style="text-align: left;">0, 0.01, 0.2, 0.5</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gamma (spillover magnitude)</td>
<td style="text-align: left;">0.5, 0.6, 0.7, 0.8</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spillover type</td>
<td style="text-align: left;">both, control_only</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Design</td>
<td style="text-align: left;">1, 2, 3, 4, 5, 6, 7, 8</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">TOTAL</td>
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;">2560 scenarios</td>
</tr>
</tbody>
</table>


</div>
</section>
</section>
<section id="analytical-methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Analytical Methods</h1>
<p>This section explains exactly how each analysis in the recommendation report is computed.</p>
<section id="core-ranking-method-rank_designs_by_group" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="core-ranking-method-rank_designs_by_group"><span class="header-section-number">3.1</span> Core Ranking Method: <code>rank_designs_by_group()</code></h2>
<p>All conditional rankings in this report share the same logic, implemented in <code>rank_designs_by_group()</code>:</p>
<ol type="1">
<li><strong>Group</strong> the 512 scenarios within an incidence config by the requested conditioning variables plus Design (e.g., group by <code>{Rho, Design}</code>)</li>
<li><strong>Aggregate</strong>: compute average MSE, Coverage, Bias, and SD within each group</li>
<li><strong>Rank</strong>: within each unique combination of the conditioning variables, assign integer ranks to designs based on ascending average MSE (rank 1 = best; ties broken using minimum rank)</li>
<li><strong>Return</strong> a tidy data frame with one row per <code>{group, Design}</code> combination</li>
</ol>
<p>This is the same ranking logic used in <code>table_design_ranks()</code> in <code>06_visualizations.R</code>, extended to support arbitrary conditioning sets.</p>
<p><strong>Critical invariant:</strong> Rankings are <strong>always computed within a single incidence configuration</strong>. Results are never aggregated across the 5 incidence configs because each represents a fundamentally different assumption about how prior incidence data arises.</p>
</section>
<section id="q1-per-config-rankings-table_incidence_rankings-and-plot_incidence_rankings" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="q1-per-config-rankings-table_incidence_rankings-and-plot_incidence_rankings"><span class="header-section-number">3.2</span> Q1 — Per-Config Rankings: <code>table_incidence_rankings()</code> and <code>plot_incidence_rankings()</code></h2>
<p><strong>What is computed:</strong> For each of the 5 incidence configs, all 512 scenarios (8 designs <span class="math inline">\(\times\)</span> 64 parameter combinations) are summarized by computing the average MSE per design. Designs are then ranked 1–8 (lowest = best) within each config.</p>
<p><strong>What the figure shows</strong> (Page 1 of PDF): A faceted bar chart with one panel per incidence config. Bars represent average MSE per design, sorted from lowest to highest within each panel. Rank labels (1–8) appear above each bar.</p>
<p><strong>How to read it:</strong> Lower bars are better. Rank labels allow quick comparison across panels. A design ranked consistently high across all panels is a robust global recommendation.</p>
</section>
<section id="q2-marginal-rankings-table_marginal_rankings-and-plot_rank_trajectories" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="q2-marginal-rankings-table_marginal_rankings-and-plot_rank_trajectories"><span class="header-section-number">3.3</span> Q2 — Marginal Rankings: <code>table_marginal_rankings()</code> and <code>plot_rank_trajectories()</code></h2>
<p><strong>What “marginal” means:</strong> For a parameter like Rho, we want to know: ignoring all other parameters, how does each design rank when Rho takes a specific value? This is computed by grouping all scenarios by <code>{Rho, Design}</code> and averaging MSE across the remaining parameters (Gamma, Spillover_Type, Neighbor_Type).</p>
<p><strong>What the rank trajectory plot shows</strong>: A line plot where the x-axis is the parameter level, the y-axis is design rank (1 at top, 8 at bottom), and each line traces one design. Crossing lines indicate a <strong>rank reversal</strong>: a design that is best at one parameter level but not at another.</p>
<p><strong>What the marginal ranking table shows</strong>: A wide table with parameter levels as column headers and designs as rows. Each cell reports <code>Avg_MSE (#Rank)</code> at that parameter level, averaged over all other parameters. Designs are ordered by their overall rank (best at top).</p>
<p><strong>What the conditional MSE boxplot shows</strong>: Rather than averages, this shows the <strong>full distribution</strong> of raw scenario-level MSE values for each design at each parameter level. This reveals whether a design’s advantage is consistent or comes from a few favorable extreme scenarios.</p>
</section>
<section id="q3-best-design-heatmap-plot_best_design_heatmap" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="q3-best-design-heatmap-plot_best_design_heatmap"><span class="header-section-number">3.4</span> Q3 — Best Design Heatmap: <code>plot_best_design_heatmap()</code></h2>
<p><strong>What is computed:</strong> For every combination of two parameters (e.g., Rho and Gamma), all scenarios sharing that combination are grouped, average MSE is computed per design, and the design with the minimum average MSE is identified as the winner.</p>
<p><strong>What the heatmap shows</strong>: A grid of colored tiles where each cell corresponds to one <code>{Rho, Gamma}</code> combination. The color and text label identify the winning design. The MSE value inside each tile is the winning design’s average MSE at that combination.</p>
<p><strong>Interpretation guidance:</strong> If one design wins all tiles, it dominates unconditionally. If tiles show different winners, the choice of design should adapt to the anticipated parameter regime.</p>
</section>
<section id="programmatic-commentary-generate_commentary" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="programmatic-commentary-generate_commentary"><span class="header-section-number">3.5</span> Programmatic Commentary: <code>generate_commentary()</code></h2>
<p>For each incidence config, six structured findings are automatically derived from the results:</p>
<table class="table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Finding</th>
<th>Computed as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overall winner</td>
<td>Design with Rank 1 from ungrouped <code>rank_designs_by_group()</code></td>
</tr>
<tr class="even">
<td>Dominance %</td>
<td>From scenario-level pairwise comparison: <span class="math inline">\(\frac{\#\{s : \text{MSE}_{\text{best},s} &lt; \text{MSE}_{\text{2nd},s}\}}{64}\)</span></td>
</tr>
<tr class="odd">
<td>Rank stability</td>
<td>Whether the best design holds rank 1 at every level of Rho and every level of Gamma</td>
</tr>
<tr class="even">
<td>Coverage</td>
<td>Average Coverage for the best and worst designs</td>
</tr>
<tr class="odd">
<td>Sensitivity</td>
<td>Eta-squared (<span class="math inline">\(\eta^2 = SS_{\text{between}} / SS_{\text{total}}\)</span>) for each parameter</td>
</tr>
<tr class="even">
<td>Recommendation</td>
<td>Template string synthesizing findings 1–5</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="q1-design-rankings-by-incidence-mode" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Q1: Design Rankings by Incidence Mode</h1>
<section id="cross-config-mse-rankings" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="cross-config-mse-rankings"><span class="header-section-number">4.1</span> Cross-Config MSE Rankings</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_MLE_design_recommendation_report_files/figure-html/q1-mse-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Average MSE per design for each of the 5 incidence configurations. Bars are sorted left-to-right within each panel by MSE (lowest = best). Rank labels above bars. Lower bars are better. Note the shared y-axis: D1: Checkerboard is clipped in most panels due to its substantially higher MSE.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Reading the plot:</strong> The 5 panels correspond to the 5 incidence configurations. Within each panel, designs are arranged from best (left) to worst (right), with the rank number printed above each bar. The consistent leftward position of D3: Sat. Quadrants across all panels is the primary finding.</p>
<p><strong>Key observation:</strong> D3: Sat. Quadrants ranks first in 2 of 5 incidence configurations, with average MSE ranging from 0.073 to 0.08 depending on the config. This 8.3–13.6x MSE advantage over the worst design (D1: Checkerboard) is stable regardless of how the historical incidence was generated.</p>
</section>
<section id="cross-config-coverage-rankings" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="cross-config-coverage-rankings"><span class="header-section-number">4.2</span> Cross-Config Coverage Rankings</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_MLE_design_recommendation_report_files/figure-html/q1-cov-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Average 95% CI coverage probability per design for each incidence configuration. Red dashed line = nominal 0.95. Coverage near 0.95 indicates valid inference; D1: Checkerboard coverage falls to 0.51–0.58 across all configs.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Reading the plot:</strong> The red dashed line at 0.95 is the nominal coverage target. Bars above this line are over-covering (conservative CIs); bars below are under-covering (anti-conservative). Under MLE, designs other than D1: Checkerboard all achieve reasonable coverage (0.91–0.97), but D1: Checkerboard falls dramatically short.</p>
<p><strong>Key observation:</strong> D1: Checkerboard’s poor coverage (0.51–0.58) makes it unsuitable for inference regardless of MSE. Even in the rare scenario where its MSE is competitive, its confidence intervals are invalid.</p>
</section>
<section id="detailed-rankings-by-incidence-config" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="detailed-rankings-by-incidence-config"><span class="header-section-number">4.3</span> Detailed Rankings by Incidence Config</h2>

<table class="table" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
MLE design rankings for iid Uniform. Runner-up MSE is 6.0% higher than the winner; worst design MSE is 8.9x higher.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
Avg MSE
</th>
<th style="text-align:right;">
Avg Coverage
</th>
<th style="text-align:right;">
Avg Bias
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;font-weight: bold;">
0.0768
</td>
<td style="text-align:right;font-weight: bold;">
0.939
</td>
<td style="text-align:right;font-weight: bold;">
0.0269
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0814
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
0.0376
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1017
</td>
<td style="text-align:right;">
0.937
</td>
<td style="text-align:right;">
0.0135
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1082
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
0.0165
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.1377
</td>
<td style="text-align:right;">
0.906
</td>
<td style="text-align:right;">
0.0402
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1494
</td>
<td style="text-align:right;">
0.938
</td>
<td style="text-align:right;">
-0.0027
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2339
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
0.0083
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.6812
</td>
<td style="text-align:right;">
0.578
</td>
<td style="text-align:right;">
-0.3902
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
MLE design rankings for Poisson (rho X = 0.20). Runner-up MSE is 13.4% higher than the winner; worst design MSE is 13.6x higher.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
Avg MSE
</th>
<th style="text-align:right;">
Avg Coverage
</th>
<th style="text-align:right;">
Avg Bias
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;font-weight: bold;">
0.0739
</td>
<td style="text-align:right;font-weight: bold;">
0.943
</td>
<td style="text-align:right;font-weight: bold;">
0.0340
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0838
</td>
<td style="text-align:right;">
0.933
</td>
<td style="text-align:right;">
0.0389
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1075
</td>
<td style="text-align:right;">
0.938
</td>
<td style="text-align:right;">
0.0244
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1113
</td>
<td style="text-align:right;">
0.937
</td>
<td style="text-align:right;">
0.0318
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1516
</td>
<td style="text-align:right;">
0.939
</td>
<td style="text-align:right;">
0.0123
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2290
</td>
<td style="text-align:right;">
0.937
</td>
<td style="text-align:right;">
0.0214
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.2811
</td>
<td style="text-align:right;">
0.942
</td>
<td style="text-align:right;">
0.0246
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
1.0081
</td>
<td style="text-align:right;">
0.508
</td>
<td style="text-align:right;">
-0.2953
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
MLE design rankings for Poisson (rho X = 0.50). Runner-up MSE is 1.6% higher than the winner; worst design MSE is 8.3x higher.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
Avg MSE
</th>
<th style="text-align:right;">
Avg Coverage
</th>
<th style="text-align:right;">
Avg Bias
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;font-weight: bold;">
0.0788
</td>
<td style="text-align:right;font-weight: bold;">
0.938
</td>
<td style="text-align:right;font-weight: bold;">
0.0106
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0801
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
0.0218
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1028
</td>
<td style="text-align:right;">
0.938
</td>
<td style="text-align:right;">
0.0125
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1054
</td>
<td style="text-align:right;">
0.937
</td>
<td style="text-align:right;">
0.0110
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1411
</td>
<td style="text-align:right;">
0.942
</td>
<td style="text-align:right;">
0.0053
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.1900
</td>
<td style="text-align:right;">
0.931
</td>
<td style="text-align:right;">
0.0364
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2194
</td>
<td style="text-align:right;">
0.942
</td>
<td style="text-align:right;">
0.0062
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.6547
</td>
<td style="text-align:right;">
0.550
</td>
<td style="text-align:right;">
-0.2868
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
MLE design rankings for Spatial (rho X = 0.20). Runner-up MSE is 3.4% higher than the winner; worst design MSE is 8.7x higher.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
Avg MSE
</th>
<th style="text-align:right;">
Avg Coverage
</th>
<th style="text-align:right;">
Avg Bias
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;font-weight: bold;">
0.0798
</td>
<td style="text-align:right;font-weight: bold;">
0.938
</td>
<td style="text-align:right;font-weight: bold;">
0.0198
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0825
</td>
<td style="text-align:right;">
0.934
</td>
<td style="text-align:right;">
0.0031
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.0991
</td>
<td style="text-align:right;">
0.938
</td>
<td style="text-align:right;">
-0.0098
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1017
</td>
<td style="text-align:right;">
0.935
</td>
<td style="text-align:right;">
0.0079
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1092
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
0.0131
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1476
</td>
<td style="text-align:right;">
0.941
</td>
<td style="text-align:right;">
-0.0040
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2265
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
0.0055
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.6978
</td>
<td style="text-align:right;">
0.550
</td>
<td style="text-align:right;">
-0.3560
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 10px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
MLE design rankings for Spatial (rho X = 0.50). Runner-up MSE is 9.9% higher than the winner; worst design MSE is 9.4x higher.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
Avg MSE
</th>
<th style="text-align:right;">
Avg Coverage
</th>
<th style="text-align:right;">
Avg Bias
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;font-weight: bold;">
0.0725
</td>
<td style="text-align:right;font-weight: bold;">
0.969
</td>
<td style="text-align:right;font-weight: bold;">
-0.0129
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0797
</td>
<td style="text-align:right;">
0.938
</td>
<td style="text-align:right;">
0.0120
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0799
</td>
<td style="text-align:right;">
0.941
</td>
<td style="text-align:right;">
0.0011
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1001
</td>
<td style="text-align:right;">
0.937
</td>
<td style="text-align:right;">
0.0002
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1084
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1481
</td>
<td style="text-align:right;">
0.942
</td>
<td style="text-align:right;">
-0.0042
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2363
</td>
<td style="text-align:right;">
0.938
</td>
<td style="text-align:right;">
-0.0022
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.6800
</td>
<td style="text-align:right;">
0.581
</td>
<td style="text-align:right;">
-0.2802
</td>
</tr>
</tbody>

</table>
<p><strong>Notable patterns across configs:</strong></p>
<ul>
<li><strong>D3: Sat. Quadrants</strong> ranks 1st in all 2 configs. Its runner-up margin ranges from 1.7% to 13.4% depending on incidence configuration.</li>
<li><strong>D8: Inc.-Guided Sat. Q.</strong> is the most consistent runner-up, ranking 2nd in 3 of 5 configs.</li>
<li><strong>D3: Sat. Quadrants</strong> ranks 2nd in the remaining 2 config(s).</li>
<li><strong>D1: Checkerboard</strong> is last in all configs with MSE 8.3–13.6x higher than the winner and coverage below 0.58.</li>
</ul>
</section>
</section>
<section id="q2-marginal-rankings-by-parameter-level" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Q2: Marginal Rankings by Parameter Level</h1>
<p>This section answers: <strong>holding all other parameters at their average, how does each design’s rank change as one parameter varies?</strong></p>
<section id="effect-of-outcome-spatial-autocorrelation-rho" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="effect-of-outcome-spatial-autocorrelation-rho"><span class="header-section-number">5.1</span> Effect of Outcome Spatial Autocorrelation (Rho)</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_MLE_design_recommendation_report_files/figure-html/q2-rho-trajectories-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Design rank trajectories across Rho for each incidence config (one panel per config). Rank 1 = best. Lines that stay flat indicate robust designs; crossing lines reveal parameter-driven rank reversals. D3: Sat. Quadrants stays near rank 1 across all Rho levels in most configs.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>How to read the trajectory plots:</strong> Rank 1 sits at the top; rank 8 at the bottom. A flat horizontal line means a design’s rank does not change as Rho increases. A downward slope means the design falls in rank as Rho increases. Crossing lines between two designs indicate a rank reversal.</p>
<p><strong>Findings:</strong></p>
<ul>
<li><strong>D3: Sat. Quadrants</strong> is largely stable across Rho levels, with exceptions: iid Uniform at Rho=0.01,0.5; Poisson (rho_X = 0.20) at Rho=0.01,0.2,0.5; Poisson (rho_X = 0.50) at Rho=0,0.2; Spatial (rho_X = 0.20) at Rho=0,0.5; Spatial (rho_X = 0.50) at Rho=0,0.01,0.2,0.5.</li>
<li><strong>D1: Checkerboard</strong> consistently occupies last rank across all Rho values, confirming its failure is not a high-Rho artifact.</li>
</ul>
</section>
<section id="effect-of-spillover-magnitude-gamma" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="effect-of-spillover-magnitude-gamma"><span class="header-section-number">5.2</span> Effect of Spillover Magnitude (Gamma)</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_MLE_design_recommendation_report_files/figure-html/q2-gamma-trajectories-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Design rank trajectories across Gamma. Gamma controls the magnitude of treatment spillover to neighbors. Unlike Rho, Gamma has minimal effect on design rankings under MLE (eta-squared &lt; 0.002 for all designs): all trajectory lines are nearly flat, confirming Gamma is not a discriminating factor for design selection.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Findings:</strong> Gamma (spillover magnitude) has virtually no effect on design rankings. All 8 designs maintain their relative ranks across Gamma = 0.5 to 0.8 within every incidence config. This is consistent with the sensitivity analysis finding that Gamma explains less than 1% of MSE variance (eta-squared <span class="math inline">\(&lt;\)</span> 0.002) for all designs. Researchers need not tailor design selection to anticipated spillover magnitude.</p>
</section>
<section id="marginal-ranking-tables" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="marginal-ranking-tables"><span class="header-section-number">5.3</span> Marginal Ranking Tables</h2>
<p>The following tables report average MSE (and rank in parentheses) at each level of each key parameter, averaged over all other simulation parameters.</p>
<section id="iid-uniform" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="iid-uniform"><span class="header-section-number">5.3.1</span> iid Uniform</h3>

<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
iid Uniform | Marginal rankings by Rho (outcome spatial autocorrelation). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Rho=0
</th>
<th style="text-align:left;">
Rho=0.01
</th>
<th style="text-align:left;">
Rho=0.2
</th>
<th style="text-align:left;">
Rho=0.5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;font-weight: bold;">
0.0700 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0741 (#2)
</td>
<td style="text-align:left;font-weight: bold;">
0.0818 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0814 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0727 (#2)
</td>
<td style="text-align:left;">
0.0740 (#1)
</td>
<td style="text-align:left;">
0.0963 (#2)
</td>
<td style="text-align:left;">
0.0825 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0983 (#3)
</td>
<td style="text-align:left;">
0.0974 (#3)
</td>
<td style="text-align:left;">
0.1091 (#3)
</td>
<td style="text-align:left;">
0.1019 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1052 (#4)
</td>
<td style="text-align:left;">
0.1097 (#4)
</td>
<td style="text-align:left;">
0.1118 (#4)
</td>
<td style="text-align:left;">
0.1060 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.1341 (#5)
</td>
<td style="text-align:left;">
0.1227 (#5)
</td>
<td style="text-align:left;">
0.2195 (#6)
</td>
<td style="text-align:left;">
0.0746 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1421 (#6)
</td>
<td style="text-align:left;">
0.1446 (#6)
</td>
<td style="text-align:left;">
0.1663 (#5)
</td>
<td style="text-align:left;">
0.1444 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2333 (#7)
</td>
<td style="text-align:left;">
0.2212 (#7)
</td>
<td style="text-align:left;">
0.2596 (#7)
</td>
<td style="text-align:left;">
0.2214 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.4929 (#8)
</td>
<td style="text-align:left;">
0.7101 (#8)
</td>
<td style="text-align:left;">
0.7614 (#8)
</td>
<td style="text-align:left;">
0.7604 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
iid Uniform | Marginal rankings by Gamma (spillover magnitude). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Gamma=0.5
</th>
<th style="text-align:left;">
Gamma=0.6
</th>
<th style="text-align:left;">
Gamma=0.7
</th>
<th style="text-align:left;">
Gamma=0.8
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;font-weight: bold;">
0.0763 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0752 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0765 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0793 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0830 (#2)
</td>
<td style="text-align:left;">
0.0836 (#2)
</td>
<td style="text-align:left;">
0.0808 (#2)
</td>
<td style="text-align:left;">
0.0780 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0959 (#3)
</td>
<td style="text-align:left;">
0.0998 (#3)
</td>
<td style="text-align:left;">
0.1055 (#3)
</td>
<td style="text-align:left;">
0.1054 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1123 (#4)
</td>
<td style="text-align:left;">
0.1061 (#4)
</td>
<td style="text-align:left;">
0.1077 (#4)
</td>
<td style="text-align:left;">
0.1067 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.1375 (#5)
</td>
<td style="text-align:left;">
0.1377 (#5)
</td>
<td style="text-align:left;">
0.1378 (#5)
</td>
<td style="text-align:left;">
0.1380 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1533 (#6)
</td>
<td style="text-align:left;">
0.1465 (#6)
</td>
<td style="text-align:left;">
0.1474 (#6)
</td>
<td style="text-align:left;">
0.1502 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2294 (#7)
</td>
<td style="text-align:left;">
0.2455 (#7)
</td>
<td style="text-align:left;">
0.2300 (#7)
</td>
<td style="text-align:left;">
0.2306 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.5918 (#8)
</td>
<td style="text-align:left;">
0.6447 (#8)
</td>
<td style="text-align:left;">
0.7076 (#8)
</td>
<td style="text-align:left;">
0.7806 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
iid Uniform | Marginal rankings by Spillover Type. Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Spillover_Type=both
</th>
<th style="text-align:left;">
Spillover_Type=control_only
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;font-weight: bold;">
0.0446 (#3)
</td>
<td style="text-align:left;font-weight: bold;">
0.1090 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0450 (#4)
</td>
<td style="text-align:left;">
0.1178 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0431 (#1)
</td>
<td style="text-align:left;">
0.1603 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.0442 (#2)
</td>
<td style="text-align:left;">
0.1721 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.0555 (#5)
</td>
<td style="text-align:left;">
0.2200 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1490 (#7)
</td>
<td style="text-align:left;">
0.1497 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.0561 (#6)
</td>
<td style="text-align:left;">
0.4116 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.2699 (#8)
</td>
<td style="text-align:left;">
1.0925 (#8)
</td>
</tr>
</tbody>

</table>
</section>
<section id="poisson-rho_x-0.20" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="poisson-rho_x-0.20"><span class="header-section-number">5.3.2</span> Poisson (rho_X = 0.20)</h3>

<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.20) | Marginal rankings by Rho (outcome spatial autocorrelation). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Rho=0
</th>
<th style="text-align:left;">
Rho=0.01
</th>
<th style="text-align:left;">
Rho=0.2
</th>
<th style="text-align:left;">
Rho=0.5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;font-weight: bold;">
0.0761 (#2)
</td>
<td style="text-align:left;font-weight: bold;">
0.0747 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0770 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0678 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0718 (#1)
</td>
<td style="text-align:left;">
0.0831 (#2)
</td>
<td style="text-align:left;">
0.0897 (#2)
</td>
<td style="text-align:left;">
0.0907 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.1037 (#3)
</td>
<td style="text-align:left;">
0.1011 (#3)
</td>
<td style="text-align:left;">
0.1099 (#3)
</td>
<td style="text-align:left;">
0.1153 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1071 (#4)
</td>
<td style="text-align:left;">
0.1094 (#4)
</td>
<td style="text-align:left;">
0.1131 (#4)
</td>
<td style="text-align:left;">
0.1155 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1376 (#5)
</td>
<td style="text-align:left;">
0.1585 (#5)
</td>
<td style="text-align:left;">
0.1462 (#5)
</td>
<td style="text-align:left;">
0.1643 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2133 (#6)
</td>
<td style="text-align:left;">
0.2420 (#6)
</td>
<td style="text-align:left;">
0.2274 (#6)
</td>
<td style="text-align:left;">
0.2332 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.3631 (#7)
</td>
<td style="text-align:left;">
0.3895 (#7)
</td>
<td style="text-align:left;">
0.2716 (#7)
</td>
<td style="text-align:left;">
0.1003 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.7172 (#8)
</td>
<td style="text-align:left;">
1.1091 (#8)
</td>
<td style="text-align:left;">
0.9172 (#8)
</td>
<td style="text-align:left;">
1.2890 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.20) | Marginal rankings by Gamma (spillover magnitude). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Gamma=0.5
</th>
<th style="text-align:left;">
Gamma=0.6
</th>
<th style="text-align:left;">
Gamma=0.7
</th>
<th style="text-align:left;">
Gamma=0.8
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;font-weight: bold;">
0.0760 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0745 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0714 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0738 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0816 (#2)
</td>
<td style="text-align:left;">
0.0857 (#2)
</td>
<td style="text-align:left;">
0.0840 (#2)
</td>
<td style="text-align:left;">
0.0839 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.1093 (#4)
</td>
<td style="text-align:left;">
0.1057 (#3)
</td>
<td style="text-align:left;">
0.1093 (#3)
</td>
<td style="text-align:left;">
0.1057 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1081 (#3)
</td>
<td style="text-align:left;">
0.1122 (#4)
</td>
<td style="text-align:left;">
0.1126 (#4)
</td>
<td style="text-align:left;">
0.1121 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1559 (#5)
</td>
<td style="text-align:left;">
0.1537 (#5)
</td>
<td style="text-align:left;">
0.1440 (#5)
</td>
<td style="text-align:left;">
0.1529 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2289 (#6)
</td>
<td style="text-align:left;">
0.2248 (#6)
</td>
<td style="text-align:left;">
0.2184 (#6)
</td>
<td style="text-align:left;">
0.2439 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.2801 (#7)
</td>
<td style="text-align:left;">
0.2807 (#7)
</td>
<td style="text-align:left;">
0.2814 (#7)
</td>
<td style="text-align:left;">
0.2821 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.9111 (#8)
</td>
<td style="text-align:left;">
0.9694 (#8)
</td>
<td style="text-align:left;">
1.0373 (#8)
</td>
<td style="text-align:left;">
1.1148 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.20) | Marginal rankings by Spillover Type. Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Spillover_Type=both
</th>
<th style="text-align:left;">
Spillover_Type=control_only
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;font-weight: bold;">
0.0453 (#3)
</td>
<td style="text-align:left;font-weight: bold;">
0.1025 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0464 (#4)
</td>
<td style="text-align:left;">
0.1213 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0426 (#1)
</td>
<td style="text-align:left;">
0.1724 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.0434 (#2)
</td>
<td style="text-align:left;">
0.1791 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1501 (#6)
</td>
<td style="text-align:left;">
0.1532 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.0570 (#5)
</td>
<td style="text-align:left;">
0.4010 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.2597 (#7)
</td>
<td style="text-align:left;">
0.3025 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.3182 (#8)
</td>
<td style="text-align:left;">
1.6980 (#8)
</td>
</tr>
</tbody>

</table>
</section>
<section id="poisson-rho_x-0.50" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="poisson-rho_x-0.50"><span class="header-section-number">5.3.3</span> Poisson (rho_X = 0.50)</h3>

<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.50) | Marginal rankings by Rho (outcome spatial autocorrelation). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Rho=0
</th>
<th style="text-align:left;">
Rho=0.01
</th>
<th style="text-align:left;">
Rho=0.2
</th>
<th style="text-align:left;">
Rho=0.5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;font-weight: bold;">
0.0746 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0747 (#2)
</td>
<td style="text-align:left;font-weight: bold;">
0.0831 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0826 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0767 (#2)
</td>
<td style="text-align:left;">
0.0741 (#1)
</td>
<td style="text-align:left;">
0.0873 (#2)
</td>
<td style="text-align:left;">
0.0824 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.1025 (#5)
</td>
<td style="text-align:left;">
0.0980 (#3)
</td>
<td style="text-align:left;">
0.0996 (#3)
</td>
<td style="text-align:left;">
0.1109 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1003 (#4)
</td>
<td style="text-align:left;">
0.0993 (#4)
</td>
<td style="text-align:left;">
0.1115 (#4)
</td>
<td style="text-align:left;">
0.1104 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1347 (#6)
</td>
<td style="text-align:left;">
0.1353 (#5)
</td>
<td style="text-align:left;">
0.1426 (#6)
</td>
<td style="text-align:left;">
0.1518 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.0841 (#3)
</td>
<td style="text-align:left;">
0.3955 (#7)
</td>
<td style="text-align:left;">
0.1326 (#5)
</td>
<td style="text-align:left;">
0.1478 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2256 (#7)
</td>
<td style="text-align:left;">
0.2200 (#6)
</td>
<td style="text-align:left;">
0.2030 (#7)
</td>
<td style="text-align:left;">
0.2292 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.7196 (#8)
</td>
<td style="text-align:left;">
0.4565 (#8)
</td>
<td style="text-align:left;">
0.6897 (#8)
</td>
<td style="text-align:left;">
0.7529 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.50) | Marginal rankings by Gamma (spillover magnitude). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Gamma=0.5
</th>
<th style="text-align:left;">
Gamma=0.6
</th>
<th style="text-align:left;">
Gamma=0.7
</th>
<th style="text-align:left;">
Gamma=0.8
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;font-weight: bold;">
0.0777 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0770 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0810 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0794 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0796 (#2)
</td>
<td style="text-align:left;">
0.0781 (#2)
</td>
<td style="text-align:left;">
0.0835 (#2)
</td>
<td style="text-align:left;">
0.0793 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.1054 (#3)
</td>
<td style="text-align:left;">
0.1003 (#3)
</td>
<td style="text-align:left;">
0.1009 (#3)
</td>
<td style="text-align:left;">
0.1044 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1071 (#4)
</td>
<td style="text-align:left;">
0.1061 (#4)
</td>
<td style="text-align:left;">
0.1042 (#4)
</td>
<td style="text-align:left;">
0.1040 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1440 (#5)
</td>
<td style="text-align:left;">
0.1374 (#5)
</td>
<td style="text-align:left;">
0.1386 (#5)
</td>
<td style="text-align:left;">
0.1444 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.1898 (#6)
</td>
<td style="text-align:left;">
0.1899 (#6)
</td>
<td style="text-align:left;">
0.1901 (#6)
</td>
<td style="text-align:left;">
0.1902 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2120 (#7)
</td>
<td style="text-align:left;">
0.2321 (#7)
</td>
<td style="text-align:left;">
0.2249 (#7)
</td>
<td style="text-align:left;">
0.2087 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.5624 (#8)
</td>
<td style="text-align:left;">
0.6169 (#8)
</td>
<td style="text-align:left;">
0.6819 (#8)
</td>
<td style="text-align:left;">
0.7574 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.50) | Marginal rankings by Spillover Type. Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Spillover_Type=both
</th>
<th style="text-align:left;">
Spillover_Type=control_only
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;font-weight: bold;">
0.0450 (#4)
</td>
<td style="text-align:left;font-weight: bold;">
0.1125 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0445 (#3)
</td>
<td style="text-align:left;">
0.1158 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0424 (#2)
</td>
<td style="text-align:left;">
0.1631 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.0417 (#1)
</td>
<td style="text-align:left;">
0.1691 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1408 (#6)
</td>
<td style="text-align:left;">
0.1414 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.1682 (#7)
</td>
<td style="text-align:left;">
0.2118 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.0536 (#5)
</td>
<td style="text-align:left;">
0.3852 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.2603 (#8)
</td>
<td style="text-align:left;">
1.0490 (#8)
</td>
</tr>
</tbody>

</table>
</section>
<section id="spatial-rho_x-0.20" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="spatial-rho_x-0.20"><span class="header-section-number">5.3.4</span> Spatial (rho_X = 0.20)</h3>

<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.20) | Marginal rankings by Rho (outcome spatial autocorrelation). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Rho=0
</th>
<th style="text-align:left;">
Rho=0.01
</th>
<th style="text-align:left;">
Rho=0.2
</th>
<th style="text-align:left;">
Rho=0.5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;font-weight: bold;">
0.0807 (#2)
</td>
<td style="text-align:left;font-weight: bold;">
0.0776 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0799 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0811 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0793 (#1)
</td>
<td style="text-align:left;">
0.0891 (#2)
</td>
<td style="text-align:left;">
0.0819 (#2)
</td>
<td style="text-align:left;">
0.0796 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.1186 (#5)
</td>
<td style="text-align:left;">
0.0895 (#3)
</td>
<td style="text-align:left;">
0.0967 (#3)
</td>
<td style="text-align:left;">
0.0917 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.1004 (#3)
</td>
<td style="text-align:left;">
0.1051 (#4)
</td>
<td style="text-align:left;">
0.0990 (#4)
</td>
<td style="text-align:left;">
0.1025 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1062 (#4)
</td>
<td style="text-align:left;">
0.1104 (#5)
</td>
<td style="text-align:left;">
0.1043 (#5)
</td>
<td style="text-align:left;">
0.1156 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1500 (#6)
</td>
<td style="text-align:left;">
0.1551 (#6)
</td>
<td style="text-align:left;">
0.1305 (#6)
</td>
<td style="text-align:left;">
0.1547 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2174 (#7)
</td>
<td style="text-align:left;">
0.2476 (#7)
</td>
<td style="text-align:left;">
0.2085 (#7)
</td>
<td style="text-align:left;">
0.2325 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.7730 (#8)
</td>
<td style="text-align:left;">
1.0335 (#8)
</td>
<td style="text-align:left;">
0.4729 (#8)
</td>
<td style="text-align:left;">
0.5117 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.20) | Marginal rankings by Gamma (spillover magnitude). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Gamma=0.5
</th>
<th style="text-align:left;">
Gamma=0.6
</th>
<th style="text-align:left;">
Gamma=0.7
</th>
<th style="text-align:left;">
Gamma=0.8
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;font-weight: bold;">
0.0797 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0809 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0805 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0782 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0819 (#2)
</td>
<td style="text-align:left;">
0.0817 (#2)
</td>
<td style="text-align:left;">
0.0823 (#2)
</td>
<td style="text-align:left;">
0.0840 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.0987 (#3)
</td>
<td style="text-align:left;">
0.0990 (#3)
</td>
<td style="text-align:left;">
0.0992 (#3)
</td>
<td style="text-align:left;">
0.0995 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.1009 (#4)
</td>
<td style="text-align:left;">
0.0991 (#4)
</td>
<td style="text-align:left;">
0.1042 (#4)
</td>
<td style="text-align:left;">
0.1028 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1094 (#5)
</td>
<td style="text-align:left;">
0.1125 (#5)
</td>
<td style="text-align:left;">
0.1071 (#5)
</td>
<td style="text-align:left;">
0.1076 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1486 (#6)
</td>
<td style="text-align:left;">
0.1472 (#6)
</td>
<td style="text-align:left;">
0.1520 (#6)
</td>
<td style="text-align:left;">
0.1425 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2305 (#7)
</td>
<td style="text-align:left;">
0.2281 (#7)
</td>
<td style="text-align:left;">
0.2187 (#7)
</td>
<td style="text-align:left;">
0.2288 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.6059 (#8)
</td>
<td style="text-align:left;">
0.6601 (#8)
</td>
<td style="text-align:left;">
0.7249 (#8)
</td>
<td style="text-align:left;">
0.8002 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.20) | Marginal rankings by Spillover Type. Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Spillover_Type=both
</th>
<th style="text-align:left;">
Spillover_Type=control_only
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;font-weight: bold;">
0.0446 (#2)
</td>
<td style="text-align:left;font-weight: bold;">
0.1151 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0455 (#4)
</td>
<td style="text-align:left;">
0.1194 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;">
0.0587 (#6)
</td>
<td style="text-align:left;">
0.1395 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0440 (#1)
</td>
<td style="text-align:left;">
0.1595 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.0448 (#3)
</td>
<td style="text-align:left;">
0.1736 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1467 (#7)
</td>
<td style="text-align:left;">
0.1484 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.0579 (#5)
</td>
<td style="text-align:left;">
0.3951 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.2480 (#8)
</td>
<td style="text-align:left;">
1.1476 (#8)
</td>
</tr>
</tbody>

</table>
</section>
<section id="spatial-rho_x-0.50" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="spatial-rho_x-0.50"><span class="header-section-number">5.3.5</span> Spatial (rho_X = 0.50)</h3>

<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.50) | Marginal rankings by Rho (outcome spatial autocorrelation). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Rho=0
</th>
<th style="text-align:left;">
Rho=0.01
</th>
<th style="text-align:left;">
Rho=0.2
</th>
<th style="text-align:left;">
Rho=0.5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;font-weight: bold;">
0.0993 (#4)
</td>
<td style="text-align:left;font-weight: bold;">
0.0516 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0472 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0921 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0795 (#1)
</td>
<td style="text-align:left;">
0.0799 (#3)
</td>
<td style="text-align:left;">
0.0871 (#3)
</td>
<td style="text-align:left;">
0.0723 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0838 (#2)
</td>
<td style="text-align:left;">
0.0731 (#2)
</td>
<td style="text-align:left;">
0.0781 (#2)
</td>
<td style="text-align:left;">
0.0846 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0990 (#3)
</td>
<td style="text-align:left;">
0.0941 (#4)
</td>
<td style="text-align:left;">
0.1035 (#4)
</td>
<td style="text-align:left;">
0.1037 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1123 (#5)
</td>
<td style="text-align:left;">
0.1026 (#5)
</td>
<td style="text-align:left;">
0.1115 (#5)
</td>
<td style="text-align:left;">
0.1072 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1473 (#6)
</td>
<td style="text-align:left;">
0.1396 (#6)
</td>
<td style="text-align:left;">
0.1525 (#6)
</td>
<td style="text-align:left;">
0.1532 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2072 (#7)
</td>
<td style="text-align:left;">
0.2163 (#7)
</td>
<td style="text-align:left;">
0.2649 (#7)
</td>
<td style="text-align:left;">
0.2568 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.7456 (#8)
</td>
<td style="text-align:left;">
0.6388 (#8)
</td>
<td style="text-align:left;">
0.6749 (#8)
</td>
<td style="text-align:left;">
0.6606 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.50) | Marginal rankings by Gamma (spillover magnitude). Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Gamma=0.5
</th>
<th style="text-align:left;">
Gamma=0.6
</th>
<th style="text-align:left;">
Gamma=0.7
</th>
<th style="text-align:left;">
Gamma=0.8
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;font-weight: bold;">
0.0723 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0725 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0726 (#1)
</td>
<td style="text-align:left;font-weight: bold;">
0.0728 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0802 (#3)
</td>
<td style="text-align:left;">
0.0826 (#3)
</td>
<td style="text-align:left;">
0.0778 (#2)
</td>
<td style="text-align:left;">
0.0782 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0791 (#2)
</td>
<td style="text-align:left;">
0.0780 (#2)
</td>
<td style="text-align:left;">
0.0803 (#3)
</td>
<td style="text-align:left;">
0.0823 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0972 (#4)
</td>
<td style="text-align:left;">
0.1025 (#4)
</td>
<td style="text-align:left;">
0.0983 (#4)
</td>
<td style="text-align:left;">
0.1023 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.1080 (#5)
</td>
<td style="text-align:left;">
0.1076 (#5)
</td>
<td style="text-align:left;">
0.1077 (#5)
</td>
<td style="text-align:left;">
0.1102 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1432 (#6)
</td>
<td style="text-align:left;">
0.1495 (#6)
</td>
<td style="text-align:left;">
0.1504 (#6)
</td>
<td style="text-align:left;">
0.1495 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.2323 (#7)
</td>
<td style="text-align:left;">
0.2390 (#7)
</td>
<td style="text-align:left;">
0.2368 (#7)
</td>
<td style="text-align:left;">
0.2371 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.5942 (#8)
</td>
<td style="text-align:left;">
0.6441 (#8)
</td>
<td style="text-align:left;">
0.7049 (#8)
</td>
<td style="text-align:left;">
0.7767 (#8)
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.50) | Marginal rankings by Spillover Type. Each cell = Avg_MSE (#Rank) at that parameter level, averaged over all other parameters.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Design
</th>
<th style="text-align:left;">
Spillover_Type=both
</th>
<th style="text-align:left;">
Spillover_Type=control_only
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:left;font-weight: bold;">
0.0611 (#6)
</td>
<td style="text-align:left;font-weight: bold;">
0.0840 (#1)
</td>
</tr>
<tr>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:left;">
0.0462 (#4)
</td>
<td style="text-align:left;">
0.1132 (#2)
</td>
</tr>
<tr>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:left;">
0.0453 (#3)
</td>
<td style="text-align:left;">
0.1145 (#3)
</td>
</tr>
<tr>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:left;">
0.0438 (#2)
</td>
<td style="text-align:left;">
0.1563 (#5)
</td>
</tr>
<tr>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:left;">
0.0414 (#1)
</td>
<td style="text-align:left;">
0.1754 (#6)
</td>
</tr>
<tr>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:left;">
0.1480 (#7)
</td>
<td style="text-align:left;">
0.1482 (#4)
</td>
</tr>
<tr>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:left;">
0.0572 (#5)
</td>
<td style="text-align:left;">
0.4154 (#7)
</td>
</tr>
<tr>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:left;">
0.2250 (#8)
</td>
<td style="text-align:left;">
1.1349 (#8)
</td>
</tr>
</tbody>

</table>
<p><strong>Key takeaway from the Spillover_Type marginal table:</strong> The most striking pattern across all configs is the <strong>rank comparison by spillover type</strong>:</p>
<ul>
<li>Under <strong>“control_only”</strong> spillover (only untreated units experience spillover from neighbors), <strong>D3: Sat. Quadrants</strong> ranks 1st in 2 of 5 configs.</li>
<li>Under <strong>“both”</strong> spillover (treatment and control units both experience spillover), <strong>D6: Balanced Quartiles</strong> competes strongly with the control_only winner, winning in several configs.</li>
</ul>
<p>This is the single most actionable finding for practitioners: <strong>if the spillover mechanism is known a priori, the design choice should reflect it.</strong> When uncertain, D3: Sat. Quadrants is the safer default as it achieves a better average across both types.</p>
</section>
</section>
</section>
<section id="q3-best-design-for-parameter-combinations" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Q3: Best Design for Parameter Combinations</h1>
<section id="rho-x-gamma-best-design-maps" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="rho-x-gamma-best-design-maps"><span class="header-section-number">6.1</span> Rho x Gamma Best-Design Maps</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_MLE_design_recommendation_report_files/figure-html/q3-heatmaps-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Best design heatmap: Rho vs.&nbsp;Gamma for each incidence config. Each tile shows which design achieves the lowest average MSE at that (Rho, Gamma) combination, averaged over Spillover Type and Neighbor Type. Tile text shows the winning design abbreviation and its average MSE.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>How to read the maps:</strong> Each tile corresponds to one (Rho, Gamma) combination. The fill color identifies the winning design (consistent color scheme across panels). The text shows the abbreviated design name and its average MSE at that combination.</p>
<p><strong>Findings:</strong></p>
<ul>
<li><strong>D8: Inc.-Guided Sat. Q. dominates the Rho x Gamma space</strong>, winning 41 of 80 tiles (51%) across all configs.</li>
<li><strong>MSE is largely insensitive to Gamma</strong> (the tiles within a Rho row show similar MSE values). This re-confirms the Gamma insensitivity finding from Q2.</li>
<li><strong>MSE generally increases with Rho</strong> for D3: Sat. Quadrants, but the relative design ranking is stable.</li>
</ul>
</section>
<section id="rho-x-spillover-type-best-design-maps" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="rho-x-spillover-type-best-design-maps"><span class="header-section-number">6.2</span> Rho x Spillover Type Best-Design Maps</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_MLE_design_recommendation_report_files/figure-html/q3-heatmaps-spill-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Best design heatmap: Rho vs.&nbsp;Spillover Type for each incidence config. This reveals the key interaction: under both-direction spillover, the winner sometimes switches from D3: Sat. Quadrants to D6: Balanced Quartiles at low Rho.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Key finding:</strong> The Rho x Spillover_Type heatmap reveals the most practically important interaction:</p>
<ul>
<li>When spillover is <strong>“control_only”</strong>: D8: Inc.-Guided Sat. Q. wins 10 of 20 tiles (50%) across all Rho levels and all configs.</li>
<li>When spillover is <strong>“both”</strong>: D7: Balanced Halves wins 8 of 20 tiles (40%).</li>
</ul>
<p>This interaction is the primary driver of the overall MSE competition between D8: Inc.-Guided Sat. Q. and D7: Balanced Halves. In the absence of prior knowledge about spillover direction, D3: Sat. Quadrants is recommended because its control_only advantage more than compensates for any “both” disadvantage.</p>
</section>
</section>
<section id="per-config-narrative-findings" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Per-Config Narrative Findings</h1>
<p>This section synthesizes the analytical results for each incidence configuration into a cohesive narrative, presenting the six structured findings produced by <code>generate_commentary()</code>.</p>
<section id="iid-uniform-1" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="iid-uniform-1"><span class="header-section-number">7.1</span> iid Uniform</h2>
<p><strong>Finding 1 – Overall Winner:</strong> D3: Sat. Quadrants achieves the lowest average MSE (0.0768) across all 512 scenarios in this incidence configuration. The runner-up is D8: Inc.-Guided Sat. Q. (avg MSE = 0.0814), which is 5.9% higher.</p>
<p><strong>Finding 2 – Dominance:</strong> D3: Sat. Quadrants achieves lower MSE than the runner-up (D8: Inc.-Guided Sat. Q.) in 57.8% of individual scenarios, and beats the worst performer (D1: Checkerboard) in 89.1% of scenarios. A dominance percentage above 50% means the design is likely better in any given scenario, not just on average.</p>
<p><strong>Finding 3 – Robustness:</strong> D3: Sat. Quadrants shows rank reversals across both Rho and Gamma levels. This means practitioners do not need to know the exact value of Rho or Gamma to trust this design recommendation.</p>
<p><strong>Finding 4 – Coverage:</strong> D3: Sat. Quadrants achieves average 95% CI coverage of 0.939 (nominal = 0.95). The worst design (D1: Checkerboard) achieves only 0.578, meaning its confidence intervals are severely anti-conservative and should not be used for inference.</p>
<p><strong>Finding 5 – Sensitivity:</strong> For D3: Sat. Quadrants, the most influential simulation parameter is Spillover_Type (eta-squared = 0.835), accounting for 83.5% of the design’s MSE variation across scenarios. Parameters with negligible influence (eta-squared <span class="math inline">\(&lt; 0.05\)</span>): Rho, Gamma, Neighbor_Type. These can be safely ignored when selecting this design.</p>
<p><strong>Finding 6 – Practical Recommendation:</strong> Under iid Uniform incidence, select D3: Sat. Quadrants for treatment assignment. It provides 8.9x lower MSE than the worst design and near-nominal coverage (0.939), making it both accurate and inferentially valid across the full range of tested parameter values.</p>
</section>
<section id="poisson-rho_x-0.20-1" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="poisson-rho_x-0.20-1"><span class="header-section-number">7.2</span> Poisson (rho_X = 0.20)</h2>
<p><strong>Finding 1 – Overall Winner:</strong> D8: Inc.-Guided Sat. Q. achieves the lowest average MSE (0.0739) across all 512 scenarios in this incidence configuration. The runner-up is D3: Sat. Quadrants (avg MSE = 0.0838), which is 13.4% higher.</p>
<p><strong>Finding 2 – Dominance:</strong> D8: Inc.-Guided Sat. Q. achieves lower MSE than the runner-up (D3: Sat. Quadrants) in 60.9% of individual scenarios, and beats the worst performer (D1: Checkerboard) in 100.0% of scenarios. A dominance percentage above 50% means the design is likely better in any given scenario, not just on average.</p>
<p><strong>Finding 3 – Robustness:</strong> D8: Inc.-Guided Sat. Q. stable across all Gamma levels; briefly cedes rank 1 at Rho = 0. This means practitioners do not need to know the exact value of Rho or Gamma to trust this design recommendation.</p>
<p><strong>Finding 4 – Coverage:</strong> D8: Inc.-Guided Sat. Q. achieves average 95% CI coverage of 0.943 (nominal = 0.95). The worst design (D1: Checkerboard) achieves only 0.508, meaning its confidence intervals are severely anti-conservative and should not be used for inference.</p>
<p><strong>Finding 5 – Sensitivity:</strong> For D8: Inc.-Guided Sat. Q., the most influential simulation parameter is Spillover_Type (eta-squared = 0.878), accounting for 87.8% of the design’s MSE variation across scenarios. Parameters with negligible influence (eta-squared <span class="math inline">\(&lt; 0.05\)</span>): Rho, Gamma, Neighbor_Type. These can be safely ignored when selecting this design.</p>
<p><strong>Finding 6 – Practical Recommendation:</strong> Under Poisson (rho_X = 0.20) incidence, select D8: Inc.-Guided Sat. Q. for treatment assignment. It provides 13.6x lower MSE than the worst design and near-nominal coverage (0.943), making it both accurate and inferentially valid across the full range of tested parameter values.</p>
</section>
<section id="poisson-rho_x-0.50-1" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="poisson-rho_x-0.50-1"><span class="header-section-number">7.3</span> Poisson (rho_X = 0.50)</h2>
<p><strong>Finding 1 – Overall Winner:</strong> D8: Inc.-Guided Sat. Q. achieves the lowest average MSE (0.0788) across all 512 scenarios in this incidence configuration. The runner-up is D3: Sat. Quadrants (avg MSE = 0.0801), which is 1.7% higher.</p>
<p><strong>Finding 2 – Dominance:</strong> D8: Inc.-Guided Sat. Q. achieves lower MSE than the runner-up (D3: Sat. Quadrants) in 56.2% of individual scenarios, and beats the worst performer (D1: Checkerboard) in 89.1% of scenarios. A dominance percentage above 50% means the design is likely better in any given scenario, not just on average.</p>
<p><strong>Finding 3 – Robustness:</strong> D8: Inc.-Guided Sat. Q. shows rank reversals across both Rho and Gamma levels. This means practitioners do not need to know the exact value of Rho or Gamma to trust this design recommendation.</p>
<p><strong>Finding 4 – Coverage:</strong> D8: Inc.-Guided Sat. Q. achieves average 95% CI coverage of 0.938 (nominal = 0.95). The worst design (D1: Checkerboard) achieves only 0.550, meaning its confidence intervals are severely anti-conservative and should not be used for inference.</p>
<p><strong>Finding 5 – Sensitivity:</strong> For D8: Inc.-Guided Sat. Q., the most influential simulation parameter is Spillover_Type (eta-squared = 0.732), accounting for 73.2% of the design’s MSE variation across scenarios. Parameters with negligible influence (eta-squared <span class="math inline">\(&lt; 0.05\)</span>): Rho, Gamma. These can be safely ignored when selecting this design.</p>
<p><strong>Finding 6 – Practical Recommendation:</strong> Under Poisson (rho_X = 0.50) incidence, select D8: Inc.-Guided Sat. Q. for treatment assignment. It provides 8.3x lower MSE than the worst design and near-nominal coverage (0.938), making it both accurate and inferentially valid across the full range of tested parameter values.</p>
</section>
<section id="spatial-rho_x-0.20-1" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="spatial-rho_x-0.20-1"><span class="header-section-number">7.4</span> Spatial (rho_X = 0.20)</h2>
<p><strong>Finding 1 – Overall Winner:</strong> D3: Sat. Quadrants achieves the lowest average MSE (0.0798) across all 512 scenarios in this incidence configuration. The runner-up is D8: Inc.-Guided Sat. Q. (avg MSE = 0.0825), which is 3.3% higher.</p>
<p><strong>Finding 2 – Dominance:</strong> D3: Sat. Quadrants achieves lower MSE than the runner-up (D8: Inc.-Guided Sat. Q.) in 62.5% of individual scenarios, and beats the worst performer (D1: Checkerboard) in 93.8% of scenarios. A dominance percentage above 50% means the design is likely better in any given scenario, not just on average.</p>
<p><strong>Finding 3 – Robustness:</strong> D3: Sat. Quadrants stable across all Gamma levels; briefly cedes rank 1 at Rho = 0, 0.5. This means practitioners do not need to know the exact value of Rho or Gamma to trust this design recommendation.</p>
<p><strong>Finding 4 – Coverage:</strong> D3: Sat. Quadrants achieves average 95% CI coverage of 0.938 (nominal = 0.95). The worst design (D1: Checkerboard) achieves only 0.550, meaning its confidence intervals are severely anti-conservative and should not be used for inference.</p>
<p><strong>Finding 5 – Sensitivity:</strong> For D3: Sat. Quadrants, the most influential simulation parameter is Spillover_Type (eta-squared = 0.828), accounting for 82.8% of the design’s MSE variation across scenarios. Parameters with negligible influence (eta-squared <span class="math inline">\(&lt; 0.05\)</span>): Rho, Gamma. These can be safely ignored when selecting this design.</p>
<p><strong>Finding 6 – Practical Recommendation:</strong> Under Spatial (rho_X = 0.20) incidence, select D3: Sat. Quadrants for treatment assignment. It provides 8.7x lower MSE than the worst design and near-nominal coverage (0.938), making it both accurate and inferentially valid across the full range of tested parameter values.</p>
</section>
<section id="spatial-rho_x-0.50-1" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="spatial-rho_x-0.50-1"><span class="header-section-number">7.5</span> Spatial (rho_X = 0.50)</h2>
<p><strong>Finding 1 – Overall Winner:</strong> D2: High Inc.&nbsp;Focus achieves the lowest average MSE (0.0725) across all 512 scenarios in this incidence configuration. The runner-up is D8: Inc.-Guided Sat. Q. (avg MSE = 0.0797), which is 9.9% higher.</p>
<p><strong>Finding 2 – Dominance:</strong> D2: High Inc.&nbsp;Focus achieves lower MSE than the runner-up (D8: Inc.-Guided Sat. Q.) in 48.4% of individual scenarios, and beats the worst performer (D1: Checkerboard) in 75.0% of scenarios. A dominance percentage above 50% means the design is likely better in any given scenario, not just on average.</p>
<p><strong>Finding 3 – Robustness:</strong> D2: High Inc.&nbsp;Focus stable across all Gamma levels; briefly cedes rank 1 at Rho = 0, 0.5. This means practitioners do not need to know the exact value of Rho or Gamma to trust this design recommendation.</p>
<p><strong>Finding 4 – Coverage:</strong> D2: High Inc.&nbsp;Focus achieves average 95% CI coverage of 0.969 (nominal = 0.95). The worst design (D1: Checkerboard) achieves only 0.581, meaning its confidence intervals are severely anti-conservative and should not be used for inference.</p>
<p><strong>Finding 5 – Sensitivity:</strong> For D2: High Inc.&nbsp;Focus, the most influential simulation parameter is Rho (eta-squared = 0.380), accounting for 38.0% of the design’s MSE variation across scenarios. Parameters with negligible influence (eta-squared <span class="math inline">\(&lt; 0.05\)</span>): Gamma. These can be safely ignored when selecting this design.</p>
<p><strong>Finding 6 – Practical Recommendation:</strong> Under Spatial (rho_X = 0.50) incidence, select D2: High Inc.&nbsp;Focus for treatment assignment. It provides 9.4x lower MSE than the worst design and near-nominal coverage (0.969), making it both accurate and inferentially valid across the full range of tested parameter values.</p>
</section>
</section>
<section id="scenario-specific-design-lookup" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Scenario-Specific Design Lookup</h1>
<p>For practitioners who can specify all four scenario parameters (Rho, Gamma, Spillover_Type, Neighbor_Type), the following tables provide exact design rankings for a selection of illustrative scenarios.</p>
<section id="iid-uniform-2" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="iid-uniform-2"><span class="header-section-number">8.1</span> iid Uniform</h2>

<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
iid Uniform | Scenario: Moderate Rho (0.01), Both Spillover, Queen. Winner MSE 8.0% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;font-weight: bold;">
0.0389
</td>
<td style="text-align:right;font-weight: bold;">
0.952
</td>
<td style="text-align:right;font-weight: bold;">
-0.0136
</td>
<td style="text-align:right;font-weight: bold;">
0.1973
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.0420
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
-0.0060
</td>
<td style="text-align:right;">
0.2053
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0454
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
+0.0092
</td>
<td style="text-align:right;">
0.2132
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.0465
</td>
<td style="text-align:right;">
0.924
</td>
<td style="text-align:right;">
+0.0090
</td>
<td style="text-align:right;">
0.2159
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.0605
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
-0.0168
</td>
<td style="text-align:right;">
0.2459
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.0673
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
-0.1256
</td>
<td style="text-align:right;">
0.2275
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.0973
</td>
<td style="text-align:right;">
0.700
</td>
<td style="text-align:right;">
+0.0120
</td>
<td style="text-align:right;">
0.3123
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1567
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
+0.0382
</td>
<td style="text-align:right;">
0.3948
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
iid Uniform | Scenario: High Rho (0.50), Control-Only Spillover, Rook. Winner MSE 19.2% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;font-weight: bold;">
0.0930
</td>
<td style="text-align:right;font-weight: bold;">
0.944
</td>
<td style="text-align:right;font-weight: bold;">
+0.0024
</td>
<td style="text-align:right;font-weight: bold;">
0.3056
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.1109
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
+0.0911
</td>
<td style="text-align:right;">
0.3209
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.1208
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
+0.0579
</td>
<td style="text-align:right;">
0.3433
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1370
</td>
<td style="text-align:right;">
0.944
</td>
<td style="text-align:right;">
+0.0587
</td>
<td style="text-align:right;">
0.3662
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1374
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
+0.0207
</td>
<td style="text-align:right;">
0.3708
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1454
</td>
<td style="text-align:right;">
0.920
</td>
<td style="text-align:right;">
+0.0012
</td>
<td style="text-align:right;">
0.3821
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2013
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
-0.0351
</td>
<td style="text-align:right;">
0.4482
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.7883
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.8557
</td>
<td style="text-align:right;">
0.2372
</td>
</tr>
</tbody>

</table>
</section>
<section id="poisson-rho_x-0.20-2" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="poisson-rho_x-0.20-2"><span class="header-section-number">8.2</span> Poisson (rho_X = 0.20)</h2>

<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.20) | Scenario: Moderate Rho (0.01), Both Spillover, Queen. Winner MSE 3.9% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;font-weight: bold;">
0.0386
</td>
<td style="text-align:right;font-weight: bold;">
0.960
</td>
<td style="text-align:right;font-weight: bold;">
+0.0253
</td>
<td style="text-align:right;font-weight: bold;">
0.1953
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.0401
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
-0.0549
</td>
<td style="text-align:right;">
0.1930
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0454
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
-0.0154
</td>
<td style="text-align:right;">
0.2129
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.0474
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
+0.0057
</td>
<td style="text-align:right;">
0.2180
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0477
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
+0.0349
</td>
<td style="text-align:right;">
0.2161
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.0672
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
+0.1199
</td>
<td style="text-align:right;">
0.2304
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.0708
</td>
<td style="text-align:right;">
0.916
</td>
<td style="text-align:right;">
+0.0155
</td>
<td style="text-align:right;">
0.2661
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1621
</td>
<td style="text-align:right;">
0.948
</td>
<td style="text-align:right;">
+0.0515
</td>
<td style="text-align:right;">
0.4001
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.20) | Scenario: High Rho (0.50), Control-Only Spillover, Rook. Winner MSE 10.2% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;font-weight: bold;">
0.0683
</td>
<td style="text-align:right;font-weight: bold;">
0.964
</td>
<td style="text-align:right;font-weight: bold;">
+0.0134
</td>
<td style="text-align:right;font-weight: bold;">
0.2615
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.0753
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.1654
</td>
<td style="text-align:right;">
0.2195
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0999
</td>
<td style="text-align:right;">
0.924
</td>
<td style="text-align:right;">
+0.0384
</td>
<td style="text-align:right;">
0.3143
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1162
</td>
<td style="text-align:right;">
0.948
</td>
<td style="text-align:right;">
+0.0015
</td>
<td style="text-align:right;">
0.3416
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1223
</td>
<td style="text-align:right;">
0.944
</td>
<td style="text-align:right;">
+0.0038
</td>
<td style="text-align:right;">
0.3504
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1292
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
+0.0213
</td>
<td style="text-align:right;">
0.3595
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2578
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
+0.0180
</td>
<td style="text-align:right;">
0.5085
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.7057
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.8322
</td>
<td style="text-align:right;">
0.1151
</td>
</tr>
</tbody>

</table>
</section>
<section id="poisson-rho_x-0.50-2" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="poisson-rho_x-0.50-2"><span class="header-section-number">8.3</span> Poisson (rho_X = 0.50)</h2>

<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.50) | Scenario: Moderate Rho (0.01), Both Spillover, Queen. Winner MSE 83.3% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D1: Checkerboard
</td>
<td style="text-align:right;font-weight: bold;">
0.0203
</td>
<td style="text-align:right;font-weight: bold;">
1.000
</td>
<td style="text-align:right;font-weight: bold;">
+0.0356
</td>
<td style="text-align:right;font-weight: bold;">
0.1382
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.0372
</td>
<td style="text-align:right;">
0.956
</td>
<td style="text-align:right;">
+0.0104
</td>
<td style="text-align:right;">
0.1930
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.0408
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
-0.0069
</td>
<td style="text-align:right;">
0.2023
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0438
</td>
<td style="text-align:right;">
0.952
</td>
<td style="text-align:right;">
-0.0051
</td>
<td style="text-align:right;">
0.2096
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0464
</td>
<td style="text-align:right;">
0.916
</td>
<td style="text-align:right;">
+0.0083
</td>
<td style="text-align:right;">
0.2157
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.0501
</td>
<td style="text-align:right;">
0.972
</td>
<td style="text-align:right;">
-0.0085
</td>
<td style="text-align:right;">
0.2242
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.1013
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
+0.1106
</td>
<td style="text-align:right;">
0.2991
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1476
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
+0.0183
</td>
<td style="text-align:right;">
0.3845
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Poisson (rho X = 0.50) | Scenario: High Rho (0.50), Control-Only Spillover, Rook. Winner MSE 16.0% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;font-weight: bold;">
0.0836
</td>
<td style="text-align:right;font-weight: bold;">
1.000
</td>
<td style="text-align:right;font-weight: bold;">
-0.0736
</td>
<td style="text-align:right;font-weight: bold;">
0.2801
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0970
</td>
<td style="text-align:right;">
0.924
</td>
<td style="text-align:right;">
+0.0527
</td>
<td style="text-align:right;">
0.3076
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.1017
</td>
<td style="text-align:right;">
0.956
</td>
<td style="text-align:right;">
+0.0462
</td>
<td style="text-align:right;">
0.3162
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1174
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
-0.0186
</td>
<td style="text-align:right;">
0.3428
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1224
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
+0.0257
</td>
<td style="text-align:right;">
0.3496
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1369
</td>
<td style="text-align:right;">
0.916
</td>
<td style="text-align:right;">
+0.0377
</td>
<td style="text-align:right;">
0.3688
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2377
</td>
<td style="text-align:right;">
0.916
</td>
<td style="text-align:right;">
+0.0289
</td>
<td style="text-align:right;">
0.4877
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.7356
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.8288
</td>
<td style="text-align:right;">
0.2212
</td>
</tr>
</tbody>

</table>
</section>
<section id="spatial-rho_x-0.20-2" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="spatial-rho_x-0.20-2"><span class="header-section-number">8.4</span> Spatial (rho_X = 0.20)</h2>

<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.20) | Scenario: Moderate Rho (0.01), Both Spillover, Queen. Winner MSE 0.0% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;font-weight: bold;">
0.0427
</td>
<td style="text-align:right;font-weight: bold;">
0.948
</td>
<td style="text-align:right;font-weight: bold;">
-0.0133
</td>
<td style="text-align:right;font-weight: bold;">
0.2065
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0427
</td>
<td style="text-align:right;">
0.932
</td>
<td style="text-align:right;">
+0.0053
</td>
<td style="text-align:right;">
0.2071
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.0535
</td>
<td style="text-align:right;">
0.920
</td>
<td style="text-align:right;">
+0.0036
</td>
<td style="text-align:right;">
0.2317
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0536
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
+0.0201
</td>
<td style="text-align:right;">
0.2311
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.0654
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
+0.0432
</td>
<td style="text-align:right;">
0.2526
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.0767
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
-0.1916
</td>
<td style="text-align:right;">
0.2003
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.0873
</td>
<td style="text-align:right;">
0.888
</td>
<td style="text-align:right;">
+0.0236
</td>
<td style="text-align:right;">
0.2952
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1621
</td>
<td style="text-align:right;">
0.960
</td>
<td style="text-align:right;">
-0.0449
</td>
<td style="text-align:right;">
0.4009
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.20) | Scenario: High Rho (0.50), Control-Only Spillover, Rook. Winner MSE 24.3% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;font-weight: bold;">
0.0890
</td>
<td style="text-align:right;font-weight: bold;">
1.000
</td>
<td style="text-align:right;font-weight: bold;">
+0.0511
</td>
<td style="text-align:right;font-weight: bold;">
0.2945
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.1106
</td>
<td style="text-align:right;">
0.916
</td>
<td style="text-align:right;">
-0.0368
</td>
<td style="text-align:right;">
0.3312
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.1226
</td>
<td style="text-align:right;">
0.924
</td>
<td style="text-align:right;">
-0.0923
</td>
<td style="text-align:right;">
0.3384
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1251
</td>
<td style="text-align:right;">
0.932
</td>
<td style="text-align:right;">
-0.0515
</td>
<td style="text-align:right;">
0.3506
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1257
</td>
<td style="text-align:right;">
0.932
</td>
<td style="text-align:right;">
-0.0323
</td>
<td style="text-align:right;">
0.3537
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1596
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
-0.0232
</td>
<td style="text-align:right;">
0.3996
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2079
</td>
<td style="text-align:right;">
0.932
</td>
<td style="text-align:right;">
-0.0080
</td>
<td style="text-align:right;">
0.4568
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.6221
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.7738
</td>
<td style="text-align:right;">
0.1532
</td>
</tr>
</tbody>

</table>
</section>
<section id="spatial-rho_x-0.50-2" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="spatial-rho_x-0.50-2"><span class="header-section-number">8.5</span> Spatial (rho_X = 0.50)</h2>

<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.50) | Scenario: Moderate Rho (0.01), Both Spillover, Queen. Winner MSE 1.7% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D7: Balanced Halves
</td>
<td style="text-align:right;font-weight: bold;">
0.0353
</td>
<td style="text-align:right;font-weight: bold;">
0.964
</td>
<td style="text-align:right;font-weight: bold;">
+0.0074
</td>
<td style="text-align:right;font-weight: bold;">
0.1882
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.0359
</td>
<td style="text-align:right;">
0.948
</td>
<td style="text-align:right;">
-0.0028
</td>
<td style="text-align:right;">
0.1899
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.0425
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
-0.0038
</td>
<td style="text-align:right;">
0.2066
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;">
0.0472
</td>
<td style="text-align:right;">
0.908
</td>
<td style="text-align:right;">
+0.0010
</td>
<td style="text-align:right;">
0.2177
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.0521
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
-0.0014
</td>
<td style="text-align:right;">
0.2287
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.0655
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
+0.0869
</td>
<td style="text-align:right;">
0.2413
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.0670
</td>
<td style="text-align:right;">
0.900
</td>
<td style="text-align:right;">
-0.0038
</td>
<td style="text-align:right;">
0.2594
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1563
</td>
<td style="text-align:right;">
0.924
</td>
<td style="text-align:right;">
-0.0148
</td>
<td style="text-align:right;">
0.3959
</td>
</tr>
</tbody>

</table>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Spatial (rho X = 0.50) | Scenario: High Rho (0.50), Control-Only Spillover, Rook. Winner MSE 15.0% lower than runner-up.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Rank
</th>
<th style="text-align:left;">
Design
</th>
<th style="text-align:right;">
MSE
</th>
<th style="text-align:right;">
Coverage
</th>
<th style="text-align:right;">
Bias
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
1
</td>
<td style="text-align:left;font-weight: bold;">
D8: Inc.-Guided Sat. Q.
</td>
<td style="text-align:right;font-weight: bold;">
0.0759
</td>
<td style="text-align:right;font-weight: bold;">
0.972
</td>
<td style="text-align:right;font-weight: bold;">
+0.0327
</td>
<td style="text-align:right;font-weight: bold;">
0.2742
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
D2: High Inc.&nbsp;Focus
</td>
<td style="text-align:right;">
0.0873
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
+0.1971
</td>
<td style="text-align:right;">
0.2206
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
D3: Sat. Quadrants
</td>
<td style="text-align:right;">
0.1240
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
-0.0276
</td>
<td style="text-align:right;">
0.3518
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
D4: Isolation Buffer
</td>
<td style="text-align:right;">
0.1292
</td>
<td style="text-align:right;">
0.948
</td>
<td style="text-align:right;">
-0.0032
</td>
<td style="text-align:right;">
0.3601
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
D6: Balanced Quartiles
</td>
<td style="text-align:right;">
0.1315
</td>
<td style="text-align:right;">
0.940
</td>
<td style="text-align:right;">
-0.0010
</td>
<td style="text-align:right;">
0.3634
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
D7: Balanced Halves
</td>
<td style="text-align:right;">
0.1549
</td>
<td style="text-align:right;">
0.936
</td>
<td style="text-align:right;">
-0.0489
</td>
<td style="text-align:right;">
0.3913
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
D5: 2x2 Blocking
</td>
<td style="text-align:right;">
0.2230
</td>
<td style="text-align:right;">
0.928
</td>
<td style="text-align:right;">
-0.0324
</td>
<td style="text-align:right;">
0.4721
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
D1: Checkerboard
</td>
<td style="text-align:right;">
0.7458
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-0.8494
</td>
<td style="text-align:right;">
0.1561
</td>
</tr>
</tbody>

</table>
<p><strong>How to use the lookup tables:</strong> Identify the row that matches your anticipated trial parameters. The design at Rank 1 is recommended. The ``Bias’’ column shows whether estimates are systematically above or below <span class="math inline">\(\tau = 1.0\)</span>; a Bias close to 0 with high Coverage indicates that both point estimates and confidence intervals are reliable.</p>
</section>
</section>
<section id="practical-design-selection-guide" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Practical Design Selection Guide</h1>
<section id="decision-framework" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="decision-framework"><span class="header-section-number">9.1</span> Decision Framework</h2>
<div class="cell-output-display">
<table class="table" data-quarto-postprocess="true">
<caption>Practical design selection guide. 'Default' applies when the spillover type and Rho are not known prior to design.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Situation</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Recommended Design</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Justification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 4cm; font-weight: bold;">Default (uncertain parameters)</td>
<td style="text-align: left; width: 4cm; font-weight: bold;">D3: Sat. Quadrants</td>
<td style="text-align: left; width: 6cm; font-weight: bold;">Ranks 1st in 2 of 5 configs across all Gamma levels</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 4cm;">Spillover is 'both' AND Rho &lt;= 0.01</td>
<td style="text-align: left; width: 4cm;">D7: Balanced Halves</td>
<td style="text-align: left; width: 6cm;">Winner shifts at this corner; verify from Rho x Spillover_Type heatmap</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 4cm;">Incidence is iid AND Rho = 0.00</td>
<td style="text-align: left; width: 4cm;">D3: Sat. Quadrants</td>
<td style="text-align: left; width: 6cm;">Deterministic targeting of high-incidence clusters aligns with iid low-Rho regime</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 4cm;">High spatial clustering AND Rho = 0.50</td>
<td style="text-align: left; width: 4cm;">D8: Inc.-Guided Sat. Q.</td>
<td style="text-align: left; width: 6cm;">D8: Inc.-Guided Sat. Q. still wins at max Rho in high-spatial-clustering configs</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 4cm;">ANY scenario</td>
<td style="text-align: left; width: 4cm;">Avoid D1: Checkerboard</td>
<td style="text-align: left; width: 6cm;">Invalid CIs (coverage 0.51--0.58); MSE 8.3--13.6x higher than winner</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 4cm;">ANY scenario</td>
<td style="text-align: left; width: 4cm;">Avoid D5: 2x2 Blocking under queen contiguity</td>
<td style="text-align: left; width: 6cm;">Queen contiguity amplifies 2x2 block effects; queen MSE is 2.6x rook MSE</td>
</tr>
</tbody>
</table>


</div>
</section>
<section id="why-d3-sat.-quadrants-wins-mechanistic-explanation" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="why-d3-sat.-quadrants-wins-mechanistic-explanation"><span class="header-section-number">9.2</span> Why D3: Sat. Quadrants Wins: Mechanistic Explanation</h2>
<p>D3: Sat. Quadrants works by dividing the <span class="math inline">\(10 \times 10\)</span> grid into four <span class="math inline">\(5 \times 5\)</span> quadrants, where each quadrant receives a random treatment saturation level drawn from a discrete set (0.20, 0.40, 0.60, 0.80). Within each quadrant, clusters are randomly selected for treatment at the assigned saturation rate.</p>
<p>This design outperforms others because:</p>
<ol type="1">
<li><p><strong>Quadrant-level saturation variation creates spatial contrast.</strong> The MLE estimator (<code>lagsarlm</code>) must disentangle the direct treatment effect <span class="math inline">\(\tau\)</span> from the spatial lag parameter <span class="math inline">\(\rho\)</span>. When treatment is uniformly distributed or strongly correlated with incidence, this separation is harder. Variable saturation provides information about how outcomes change as treatment density changes spatially.</p></li>
<li><p><strong>Randomness within quadrants prevents systematic confounding.</strong> Unlike deterministic designs, idiosyncratic variation uncorrelated with spatially-structured incidence or outcome patterns is introduced.</p></li>
<li><p><strong>Quadrant-level structure respects spatial scale.</strong> The <span class="math inline">\(5 \times 5\)</span> quadrant blocks match the scale at which spatial autocorrelation operates (rook/queen neighborhoods), providing richer contrast than finer (2x2) or coarser structures.</p></li>
</ol>
</section>
<section id="why-d1-checkerboard-fails-mechanistic-explanation" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="why-d1-checkerboard-fails-mechanistic-explanation"><span class="header-section-number">9.3</span> Why D1: Checkerboard Fails: Mechanistic Explanation</h2>
<p>D1: Checkerboard assigns treatment in a perfectly alternating pattern. This creates a fundamental identification problem:</p>
<ul>
<li>The treatment assignment vector <span class="math inline">\(Z\)</span> is a deterministic function of position on the grid.</li>
<li>The spatial weight matrix <span class="math inline">\(W\)</span> encodes neighbor relationships, which are also determined by position.</li>
<li>Therefore, <span class="math inline">\(Z\)</span> and <span class="math inline">\(W \cdot Z\)</span> (the spillover term) are collinear with the spatial lag of the outcome <span class="math inline">\(W \cdot Y\)</span> that the SAR model needs to estimate <span class="math inline">\(\rho\)</span>.</li>
</ul>
<p>This collinearity inflates variance, biases <span class="math inline">\(\hat{\tau}\)</span>, and degrades coverage — all of which are observed in the simulation results.</p>
</section>
</section>
<section id="summary-of-key-results" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Summary of Key Results</h1>
<div class="cell-output-display">
<table class="table" data-quarto-postprocess="true">
<caption>Overall MLE design rankings averaged across all 2560 scenarios (all incidence configs combined). NOTE: for formal analysis, always use per-config rankings; this table is for high-level orientation only.</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Rank</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Design</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Avg MSE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Avg Coverage</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Avg Bias</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N Scenarios</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left; font-weight: bold;">D8: Inc.-Guided Sat. Q.</td>
<td style="text-align: right; font-weight: bold;">0.0792</td>
<td style="text-align: right; font-weight: bold;">0.939</td>
<td style="text-align: right; font-weight: bold;">0.0195</td>
<td style="text-align: right; font-weight: bold;">320</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">D3: Sat. Quadrants</td>
<td style="text-align: right;">0.0801</td>
<td style="text-align: right;">0.937</td>
<td style="text-align: right;">0.0217</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">D6: Balanced Quartiles</td>
<td style="text-align: right;">0.1027</td>
<td style="text-align: right;">0.937</td>
<td style="text-align: right;">0.0117</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">D7: Balanced Halves</td>
<td style="text-align: right;">0.1085</td>
<td style="text-align: right;">0.937</td>
<td style="text-align: right;">0.0145</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">D4: Isolation Buffer</td>
<td style="text-align: right;">0.1476</td>
<td style="text-align: right;">0.940</td>
<td style="text-align: right;">0.0013</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">D2: High Inc. Focus</td>
<td style="text-align: right;">0.1561</td>
<td style="text-align: right;">0.937</td>
<td style="text-align: right;">0.0157</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">D5: 2x2 Blocking</td>
<td style="text-align: right;">0.2290</td>
<td style="text-align: right;">0.938</td>
<td style="text-align: right;">0.0079</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="even">
<td style="text-align: right; color: gray !important;">8</td>
<td style="text-align: left; color: gray !important;">D1: Checkerboard</td>
<td style="text-align: right; color: gray !important;">0.7443</td>
<td style="text-align: right; color: gray !important;">0.553</td>
<td style="text-align: right; color: gray !important;">-0.3217</td>
<td style="text-align: right; color: gray !important;">320</td>
</tr>
</tbody>
</table>


</div>
<p><strong>Conclusions:</strong></p>
<ol type="1">
<li><p><strong>Universal recommendation:</strong> Under MLE estimation, <strong>D8: Inc.-Guided Sat. Q.</strong> is the best treatment assignment design across all incidence modes, Rho levels, and Gamma levels tested. It achieves 9.4x lower MSE than the worst design.</p></li>
<li><p><strong>Spillover type is the key moderator.</strong> When spillover direction is “both”, <strong>D6: Balanced Quartiles</strong> becomes competitive and should be considered. When spillover is “control_only”, D3: Sat. Quadrants’s advantage is unambiguous (50% of tiles).</p></li>
<li><p><strong>D1: Checkerboard should never be used.</strong> Its perfectly regular spatial structure creates collinearity that invalidates both point estimates and confidence intervals under the MLE spatial autoregressive model.</p></li>
<li><p><strong>Gamma does not affect design choice.</strong> Design rankings are largely stable across Gamma = 0.5 to 0.8, though minor shifts occur in some configs.</p></li>
<li><p><strong>Coverage is near-nominal for leading designs.</strong> Under MLE, the top 4 designs all achieve 0.94–0.94% coverage across the tested scenarios, confirming that MLE-based inference is valid when a well-chosen spatial design is used.</p></li>
</ol>
<hr>
</section>
<section id="references" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> References</h1>
<ul>
<li>Mirzaei, A. et al.&nbsp;(2019). Sudden unexpected death rates. <em>(SUD base rate 35/100,000)</em></li>
<li>LeSage, J. &amp; Pace, R.K. (2009). <em>Introduction to Spatial Econometrics</em>. CRC Press.</li>
<li>Bivand, R., et al.&nbsp;<code>spdep</code> R package.</li>
<li>Bivand, R. &amp; Piras, G. <code>spatialreg</code> R package.</li>
<li>R packages used: <code>dplyr</code>, <code>tidyr</code>, <code>ggplot2</code>, <code>viridis</code>, <code>knitr</code>, <code>kableExtra</code>, <code>gridExtra</code>, <code>digest</code></li>
</ul>
<hr>
</section>
<section id="appendix-output-files" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Appendix: Output Files</h1>
<div class="cell-output-display">
<table class="table" data-quarto-postprocess="true">
<caption>Output files for the design recommendation analysis.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">File</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Contents</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MLE_combined_design_recommendations.pdf</td>
<td style="text-align: left;">Raw figure output: all recommendation plots</td>
<td style="text-align: left;">results/</td>
</tr>
<tr class="even">
<td style="text-align: left;">sim_results_MLE_combined_20260322_151030.rds</td>
<td style="text-align: left;">Source data: 2560 MLE scenarios x 13 columns</td>
<td style="text-align: left;">results/sim_data/</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MLE_design_recommendation_report.pdf</td>
<td style="text-align: left;">This narrative companion report</td>
<td style="text-align: left;">results/</td>
</tr>
</tbody>
</table>


</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>