---
title: "Spatial Data Sim"
author: "Andrew Walther"
date: "`r Sys.Date()`"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
# load packages
library(tidyverse)
library(ggplot2)

# set seed
set.seed(2024)
```

```{r}
# generate data points
n.points <- 2000

sim_data <- data.frame(
  x = runif(n.points, min = 0, max = 1000),
  y = runif(n.points, min = 0, max = 1000)
)

# assign coordinates to intervention
sim_data$intervention <- ifelse(sim_data$x >= 333 & sim_data$x <= 666 & sim_data$y >= 333 & sim_data$y <= 666, 1, 0)

# assign coordinates to spillover area
sim_data$spillover <- ifelse(sim_data$x >= 133 & sim_data$x <= 866 & sim_data$y >= 133 & sim_data$y <= 866, 1, 0)

```

```{r}
# add "outcome" value
beta <- 2 # this is estimated somehow? specified as 2 in the paper (intervention effect)
alpha <- 0.2 # this is fixed in the paper

sim_data$outcome <- ifelse(sim_data$intervention == 1, alpha + beta, alpha)
```

```{r}
# generate simulation plot
ggplot(sim_data, aes(x = x, y = y, color = as.factor(intervention))) +
  # geom point plot
  geom_point(alpha = sim_data$outcome) +
  # Add solid line box for intervention area
  geom_rect(aes(xmin = 333, xmax = 666, ymin = 333, ymax = 666), 
            color = "springgreen4", fill = NA, linetype = "solid", size = 0.5) +
  # Add dashed line box for spillover area
  geom_rect(aes(xmin = 133, xmax = 866, ymin = 133, ymax = 866), 
            color = "springgreen4", fill = NA, linetype = "dashed", size = 0.5) +
  # color data points for intervention/control
  scale_color_manual(values = c("0" = "blue", "1" = "red"), name = "Intervention") +
  # add plot labels
  labs(title = "Spatial Points Plot with Intervention and Spillover Areas", 
       x = "X Coordinate", y = "Y Coordinate") +
  theme_classic()
```

```{r}
### Intervention vs. control observations ###
# count intervention observations
sum(sim_data$intervention == 1)

# count control observations
sum(sim_data$intervention == 0)

# count control in spillover zone
sum(sim_data$intervention == 0 & sim_data$spillover == 1)

# count control out of spillover zone
sum(sim_data$intervention == 0 & sim_data$spillover == 0)
```

```{r}
### Control observations in spillover zone ###
# Filter data for observations where intervention is 0
data_no_intervention <- sim_data[sim_data$intervention == 0, ]

# Create a contingency table for spillover status in this subset
spillover_table <- table(data_no_intervention$spillover)

# Create a proportion table
prop_spillover_table <- prop.table(spillover_table)

# Print the proportion table
print(prop_spillover_table)
```
